---
title: "Personal recommendation"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra) # for HTML and Latex tables

knitr::opts_chunk$set(echo = TRUE, fig.align="center", fig.pos = 'H')

# this allows using tikz rendering for plots with "dev=tikz"
knit_hooks$set(plot = function(x, options) {
  if ('tikz' %in% options$dev && !options$external) {
    hook_plot_tex(x, options)
  } else hook_plot_md(x, options)
})

# Fix seed for random number generator for getting consistent results in kmeans etc.
fixed_seed <- 678

# Load common MEBN package
source("mebn/v3/MEBNv3.r")

```

```{r data_loading, echo=FALSE, message=FALSE}
library(dplyr)

# Read the data description
diet_datadesc <- read.csv(file="data/diet_data_description.csv", header = TRUE, sep = ";", dec=",")

sysdimet_datadesc <- diet_datadesc[diet_datadesc$Sysdimet %in% TRUE,]

# Data preprocessing

# sysdimet <- read.csv(file="data/SYSDIMET.csv", sep=";", dec=",")
# 
# sysdimet$SUBJECT_ID <- factor(sysdimet$SUBJECT_ID)
# sysdimet$kolestrolilaakitys <- factor(sysdimet$kolestrolilaakitys)
# 
# sysdimet_ika <- read.csv(file="data/SYSDIMET_ika.csv", sep=";", dec=",")
# sysdimet_ika <- unique(sysdimet_ika)
# sysdimet_ika$SUBJECT_ID <- factor(sysdimet_ika$SUBJECT_ID)
# sysdimet2 <- sysdimet %>% inner_join(sysdimet_ika, by="SUBJECT_ID")
# 
# sysdimet2$energiakj <- sysdimet2$energia # Sysdimet-artikkelin mukaan energia on kilojouleina
# 
# sysdimet2$mufaepros <- sysdimet2$mufa * 37 / sysdimet2$energiakj * 100 # Rasvan energiakerroin on 37 kJ/g (9 kcal/g)
# sysdimet2$pufaepros <- sysdimet2$pufa * 37 / sysdimet2$energiakj * 100 # Rasvan energiakerroin on 37 kJ/g (9 kcal/g)
# sysdimet2$safaepros <- sysdimet2$safa * 37 / sysdimet2$energiakj * 100 # Rasvan energiakerroin on 37 kJ/g (9 kcal/g)
# sysdimet2$hhepros <- sysdimet2$hhydr * 17 / sysdimet2$energiakj * 100 # Hiilihydraatin energiakerroin on 17 kJ/g (4 kcal/g)
# sysdimet2$protepros <- sysdimet2$prot * 17 / sysdimet2$energiakj * 100 # Proteiinin energiakerroin on 17 kJ/g (4 kcal/g)
# sysdimet2$kuituepros <- sysdimet2$kuitu * 17 / sysdimet2$energiakj * 100 # Kuidun energiakerroin on 8 kJ/g (2 kcal/g)
# sysdimet2$kuituepros <- sysdimet2$kuitu * 17 / sysdimet2$energiakj * 100 # Kuidun energiakerroin on 8 kJ/g (2 kcal/g)
# sysdimet2$kuituepros <- sysdimet2$kuitu * 17 / sysdimet2$energiakj * 100 # Kuidun energiakerroin on 8 kJ/g (2 kcal/g)
# 
# sysdimet2$kuituepros <- sysdimet2$kuitu * 17 / sysdimet2$energiakj * 100 # Kuidun energiakerroin on 8 kJ/g (2 kcal/g)
# 
# sysdimet2$linoliepros <- sysdimet2$linoli * 37 / sysdimet2$energiakj * 100 # Rasvahappojen energia-arvo on 37 kJ/g
# sysdimet2$linoleeniepros <- sysdimet2$linoleeni * 37 / sysdimet2$energiakj * 100 # Rasvahappojen energia-arvo on 37 kJ/g
# sysdimet2$sakkaroosiepros <- sysdimet2$sakkaroosi * 17 / sysdimet2$energiakj * 100 # Sakkaroosin energia-arvo on 17 kJ/g (4 kcal/g)
# 
# sysdimet2 <- sysdimet2[order(sysdimet2$SUBJECT_ID, sysdimet2$WEEK),]
# 
# write.csv2(sysdimet2, "data/SYSDIMET_epros.csv", row.names = FALSE)

sysdimet <- read.csv(file="data/SYSDIMET_epros.csv", sep=";", dec=",")

sysdimet$SUBJECT_ID <- factor(sysdimet$SUBJECT_ID)
sysdimet$sukupuoli <- factor(sysdimet$sukupuoli)
sysdimet$kolestrolilaakitys <- factor(sysdimet$kolestrolilaakitys)

# Define how to iterate through the graph
sysdimet_predictors <- sysdimet_datadesc[sysdimet_datadesc$Order==100,]    
sysdimet_targets <- sysdimet_datadesc[sysdimet_datadesc$Order==200,]

```


```{r}

mean(sysdimet[sysdimet$sukupuoli == 0,]$fshdl) # male
mean(sysdimet[sysdimet$sukupuoli == 1,]$fshdl) # female

sd(sysdimet[sysdimet$sukupuoli == 0,]$fshdl) # male
sd(sysdimet[sysdimet$sukupuoli == 1,]$fshdl) # female

mean(sysdimet[sysdimet$ika >= 30 & sysdimet$ika <= 49,]$fsldl)
sd(sysdimet[sysdimet$ika >= 30 & sysdimet$ika <= 49,]$fsldl)

mean(sysdimet[sysdimet$ika >= 50,]$fsldl)
sd(sysdimet[sysdimet$ika >= 50,]$fsldl)


mean(sysdimet[sysdimet$ika >= 30 & sysdimet$ika <= 49,]$fskol)
sd(sysdimet[sysdimet$ika >= 30 & sysdimet$ika <= 49,]$fskol)

mean(sysdimet[sysdimet$ika >= 50,]$fskol)
sd(sysdimet[sysdimet$ika >= 50,]$fskol)

mean(sysdimet$fsins)
sd(sysdimet$fsins)

mean(sysdimet$fpgluk)
sd(sysdimet$fpgluk)

```


```{r graph, fig.height = 4, fig.width=5, echo=FALSE, fig.align = "left", fig.cap="Initial, bi-partite, network structure. The figure is plotted with iGraph package for R language (v 1.2.6, https://igraph.org/r).", echo=FALSE, message=FALSE}
library(igraph)
initial_graph <- mebn.fully_connected_bipartite_graph(sysdimet_datadesc)

V(initial_graph)$size = 10 

# - put all blood concentrations in own rank
bipa_layout <- layout_as_bipartite(initial_graph, types = V(initial_graph)$type == "100")
# - flip layout sideways, from left to right
gap <- 6
bipa_layout <- cbind(bipa_layout[,2]*gap, bipa_layout[,1])

V(initial_graph)[V(initial_graph)$type == "100"]$label.degree = pi # left side
V(initial_graph)[V(initial_graph)$type == "200"]$label.degree = 0 # right side 1.53

#plot(initial_graph,
#       layout=bipa_layout, 
#       rescale=TRUE,
#       vertex.label.color="black",
#       vertex.label.cex=0.7,
#       vertex.label.dist=3.8,
#       edge.arrow.size=0.5,
#       edge.arrow.width=1,
#       axes=FALSE,
#       margin=0,
#       layout.par = par(mar=c(0,0,0,0)))


```

```{r graph_with_gamma_qr_mv3_full, echo=TRUE, eval=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
source("mebn/v3/MEBNv3.r")

initial_graph <- mebn.fully_connected_bipartite_graph(sysdimet_datadesc)

no_holdout <- rep(0, nrow(sysdimet))

sysdimet_multivariate <- mebn.bipartite_multivariate(reaction_graph = initial_graph, 
                                   inputdata = sysdimet,
                                   targetdata = no_holdout,
                                   predictor_columns = sysdimet_predictors, 
                                   assumed_targets = sysdimet_targets, 
                                   group_column = "SUBJECT_ID",
                                   local_estimation = mebn.multivariate_sampling,
                                   local_model_cache = 
                                     "models/sysdimet/BLMM_gamma_qr_mv", 
                                   stan_model_file = "mebn/v3/BLMM_gamma_single_mv.stan",
                                   normalize_values = TRUE)

write.graph(sysdimet_multivariate, "graphs/sysdimet_gamma_qr_mv.graphml", "graphml")
```


```{r}
source("mebn/v3/MEBNv3.r")
#sysdimet_multivariate
# TODO: Update graph to friendly names

sysdimet_datadesc[sysdimet_datadesc$Name == V(sysdimet_multivariate),]$ShortDescription

graph_layout <- mebn.plot_typical_effects(sysdimet_multivariate, 20, graph_layout = bipa_layout)

```


```{r}
# Model diagnostics
library(rstan)
multivariate_model_name <- paste0(sysdimet_targets$Name, collapse = "_")

target_blmm <- mebn.get_localfit(multivariate_model_name, "models/sysdimet/BLMM_gamma_qr_mv")

stan_diag(target_blmm)
stan_rhat(target_blmm)

sumstats <- summary(target_blmm)

eff <- na.omit(sumstats$summary[,9])
c(min(eff),mean(eff),max(eff)) # 250.231  4726.991 13476.071

rhat <- na.omit(sumstats$summary[,10])
c(min(rhat),mean(rhat),max(rhat)) # 0.9990149 1.0000900 1.0125630

```


```{r sysdimet_gamma_mv_cross_2levels_ppc, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE, cache=TRUE, fig.cap="Posterior predictive check of the model where the concentrations and their parameters are stacked into one univariate model for estimating cross-model correlations."}

p <- mebn.multivariate_dens_overlays("models/sysdimet/BLMM_gamma_qr_mv", sysdimet_targets, sysdimet) 
ggsave("figures/sysdimet_ppc_gamma_qr_mv.pdf", plot = p, width = 4, height = 4)
p
```


```{r extract_personal_generative_models, eval=FALSE, echo=FALSE}
source("mebn/v3/MEBNv3.r")

# Extract generative models for patients with data from personal grouping

# - latent parameters from this model
latent_parameter_modeldir <- "models/sysdimet/BLMM_gamma_qr_mv"
#latent_parameter_modeldir <- "models/sysdimet/BLMM_gamma_qr_mv/noncentered"

# - use these predictors and targets
target_variables <- sysdimet_targets

# - output personal generative models (graphml + rv samples) in this dir
graph_dir <- "graphs/sysdimet/gamma_qr_mv/"

patients <- levels(sysdimet$SUBJECT_ID)

#for (person_id in 62:length(patients)) {
for (person_id in 1:length(patients)) {
  
  # - initial graph structure
  initial_graph <- mebn.fully_connected_bipartite_graph(sysdimet_datadesc)
  
  # - pick the estimated latent variables for all the persons
  local_distributions <- target_variables
  local_distributions$modelcache <- latent_parameter_modeldir
  
  # - get personal data, normalized and original
  
  # - statistics for the nutrition levels are calculated from normalized data (as it was in the likelihood estimation)
  predictors <- nrow(sysdimet_predictors)
  normalized_input <- sapply(1:predictors, mebn.scale_gaussians, data = sysdimet, datadesc = sysdimet_predictors, log_transform_ln = FALSE)
  normalized_input_df <- as.data.frame(normalized_input)
  
  # - pick rows for the selected person
  subject_code <- levels(sysdimet$SUBJECT_ID)[person_id]
  personal_data_df <- cbind(sysdimet$SUBJECT_ID, normalized_input_df)
  personal_data_df <- personal_data_df[personal_data_df$`sysdimet$SUBJECT_ID` == subject_code,]
  personal_data <- as.matrix(subset(personal_data_df, select = -c(`sysdimet$SUBJECT_ID`)))

  # - store also these original stats in graph
  personal_data_org <- subset(sysdimet[sysdimet$SUBJECT_ID == subject_code,], select = as.vector(sysdimet_predictors$Name))
  personal_concentrations_org <- subset(sysdimet[sysdimet$SUBJECT_ID == subject_code,], select = as.vector(sysdimet_targets$Name))
  
  personal_model_dir <- paste0(graph_dir, person_id)
  
  # Generate a personal graph in directory
  
  # one-level, univariate models
  #personal_graph <- mebn.extract_personal_graph(person_id, initial_graph, personal_model_dir, assumedpredictors, target_variables, latent_parameter_modeldir, personal_data, personal_data_org)

  # one-level model
  personal_graph <- mebn.extract_personal_graph_from_mv(person_id, initial_graph, personal_model_dir, sysdimet_predictors, sysdimet_targets, latent_parameter_modeldir, personal_data, personal_data_org, personal_concentrations_org, datadesc)

  # two-level model
  #personal_graph <- mebn.extract_multilevel_graph(person_id, group_id, initial_graph, personal_model_dir, assumedpredictors, assumedtargets, latent_parameter_modeldir, personal_data, personal_data_org, personal_concentrations_org, datadesc)
  
}

```


```{r check_failed_concs}
library(igraph)

check_failed_concs <- function(graph_person_id, personal_info, recommeded_concentrations) {
  
  fshdl_min <- recommeded_concentrations$lower_limits[1]
  fsldl_min <- recommeded_concentrations$lower_limits[2]
  fsins_min <- recommeded_concentrations$lower_limits[3]
  fskol_min <- recommeded_concentrations$lower_limits[4]
  fpgluk_min <- recommeded_concentrations$lower_limits[5]
  fshdl_max <- recommeded_concentrations$upper_limits[1]
  fsldl_max <- recommeded_concentrations$upper_limits[2]
  fsins_max <- recommeded_concentrations$upper_limits[3]
  fskol_max <- recommeded_concentrations$upper_limits[4]
  fpgluk_max <- recommeded_concentrations$upper_limits[5]  
  
  graph_dir <- paste0("graphs/sysdimet/gamma_qr_mv/",graph_person_id)
  personal_graph <- read.graph(paste0(graph_dir, "/personal_graph.graphml"), "graphml")
  
  #current_fshdl <- personal_info[personal_info$WEEK == 0,]$fshdl
  #current_fsldl <- personal_info[personal_info$WEEK == 0,]$fsldl
  #current_fsins <- personal_info[personal_info$WEEK == 0,]$fsins
  #current_fskol <- personal_info[personal_info$WEEK == 0,]$fskol
  #current_fpgluk <- personal_info[personal_info$WEEK == 0,]$fpgluk

  current_fshdl <- V(personal_graph)["fshdl"]$value_mean
  current_fsldl <- V(personal_graph)["fsldl"]$value_mean
  current_fsins <- V(personal_graph)["fsins"]$value_mean
  current_fskol <- V(personal_graph)["fskol"]$value_mean
  current_fpgluk <- V(personal_graph)["fpgluk"]$value_mean
  
  is_failing <- current_fshdl < fshdl_min | current_fshdl > fshdl_max |
    current_fsldl < fsldl_min | current_fsldl > fsldl_max |
    current_fsins < fsins_min | current_fsins > fsins_max |
    current_fskol < fskol_min | current_fskol > fskol_max |
    current_fpgluk < fpgluk_min | current_fpgluk > fpgluk_max 
  
  return(is_failing)
}

kontrolli <- unique(sysdimet[sysdimet$ryhma=='kontrolli',]$SUBJECT_ID)

```
```{r}
for (person_id in 1:length(kontrolli)) {

  subject_code <- kontrolli[person_id]

  # Normal ranges of concentration are personalized
  #personal_info <- head(sysdimet[sysdimet$SUBJECT_ID == subject_code,],1)
  #recommeded_concentrations <- mebn.get_personal_sysdimet_guidelines(personal_info)
  
  # this person_id of kontrolli is different from the whole sysdimet
  graph_person_id <- match(subject_code, levels(sysdimet$SUBJECT_ID))
  
  print(person_id)
  print(subject_code)
  print(graph_person_id)
  print("-----")
}
  
```


```{r recommendation_with_custom_utility, eval=FALSE,echo=FALSE, message=FALSE}

source("mebn/v3/MEBNv3.r")
library(igraph) 
library(dplyr)
library(ggplot2)
library(gridExtra)
  
# Query parameters
simulation <- "X50_B50_A50_I50"
#simulation <- "_lowEPA"

# - data parameters
graph_dir <- "graphs/sysdimet/gamma_qr_mv/"

datadesc <- sysdimet_datadesc

assumedpredictors <- sysdimet_predictors
assumedtargets <- sysdimet_targets

# Calculate statistics for normalizing the data

org_stats <- data.frame(name = subset(assumedpredictors$Name, assumedpredictors$Distribution == "Gaussian"))
org_stats$mean <- sapply(org_stats$name, function(x) mean(sysdimet[[x]]))
org_stats$sd <- sapply(org_stats$name, function(x) sd(sysdimet[[x]]))

queried_nodes <- as.vector(datadesc[datadesc$Condition >= 100,]$Name)

# intake bounds and RI are normalized
lowerbounds <- sapply(queried_nodes, function(x) (as.numeric(datadesc[datadesc$Name==x,]$Lowerbound) - org_stats[org_stats$name == x,]$mean) / org_stats[org_stats$name == x,]$sd)
upperbounds <- sapply(queried_nodes, function(x) (as.numeric(datadesc[datadesc$Name==x,]$Upperbound) - org_stats[org_stats$name == x,]$mean) / org_stats[org_stats$name == x,]$sd)

# generally recommended intake (RI)
RI <- sapply(queried_nodes, function(x) (as.numeric(datadesc[datadesc$Name==x,]$Recommendation) - org_stats[org_stats$name == x,]$mean) / org_stats[org_stats$name == x,]$sd)

# use middle of the lower and upperbounds as recommended level, if it has not been set
boundmids <- (lowerbounds + upperbounds)/2
RI[is.na(RI)] <- sapply(names(RI[is.na(RI)]), function(x) boundmids[[x]])

# - collect personal statistics in this data frame
patient_summary <- data.frame(matrix(ncol = 3 + length(queried_nodes) * 3 + nrow(assumedtargets) * 3, nrow = 0), row.names = NULL)

colnames(patient_summary) <- c("person_id", "subject_code", "accepted", paste0(queried_nodes), paste0(queried_nodes, "_lCI"), paste0(queried_nodes, "_uCI"), assumedtargets$Name, paste0(assumedtargets$Name, "_lCI"), paste0(assumedtargets$Name, "_uCI"))

kontrolli <- unique(sysdimet[sysdimet$ryhma=='kontrolli',]$SUBJECT_ID)

for (person_id in 1:length(kontrolli)) {

# 104 / 3 -- c vit korkealla ja myös insu ja gluc.. siksikö? joo
# personal_cvit_fpgluk = -0.02382

#for (person_id in 3:3) {
  
  subject_code <- kontrolli[person_id]

  # Normal ranges of concentration are personalized
  personal_info <- head(sysdimet[sysdimet$SUBJECT_ID == subject_code,],1)
  recommeded_concentrations <- mebn.get_personal_sysdimet_guidelines(personal_info)
  
  # this person_id of kontrolli is different from the whole sysdimet
  graph_person_id <- match(subject_code, levels(sysdimet$SUBJECT_ID))

  if (check_failed_concs(graph_person_id, personal_info, recommeded_concentrations) == TRUE) { 
  
      print(paste0("Simulating person_id ", person_id))
      print(paste0("Simulating graph_person_id ", graph_person_id))
      print(paste0("Simulating subject_code ", subject_code))
    
      personal_model_dir <- paste0(graph_dir,graph_person_id)
      personal_graph <- read.graph(paste0(personal_model_dir, "/personal_graph.graphml"), "graphml")
      
      # Sample diet proposals and matching concentration predictions
      
      l3 <- 40
      l5 <- 2
      
      # - more loose preference for special cases
      if (graph_person_id == 12 || graph_person_id == 84)
      {
        l3 <- 35
        l5 <- 1.5
      } else if (graph_person_id == 26 || graph_person_id == 28)
      {
        l3 <- 30
        l5 <- 1.1
      }
      
      intake_model <- mebn.Query(reaction_graph = personal_graph,
                               graph_dir = personal_model_dir,
                               queried_nodes = queried_nodes,
                               query = recommeded_concentrations,
                               proposal_lowerlimits = lowerbounds,
                               proposal_upperlimits = upperbounds,
                               general_RI = RI,
                               stan_model_file = "diet/recommendation_model.stan",
                               conc_lower_limits = as.vector(recommeded_concentrations$lower_limits),
                               conc_upper_limits = as.vector(recommeded_concentrations$upper_limits),
                               beta_point_est = "mean",
                               param_point_est = "mean",
                               X_point_est = "mean",
                               posterior_samples = 500,
                               repeat_only = 0,
                               verbose = 1,
                               l1 = 8,      # bound_steepness: Steepness parameter for individual soft bounds
                               l2 = 15,     # bound_requirement: Requirement for meeting all bounds
                               l3 = l3,     # preference_strength: Weighting for preference in the model
                               l4 = 30,     # transition_steepness: Steepness for the transition between model components
                               l5 = l5,     # penalty_rate: Rate at which preference errors are penalized
                               l6 = 10)     # general_recommendation_prior: Weight for general recommendation in proposal distributions 

        #params <- readRDS("last_params.rds")
        #params
      
      # Extract all the samples and correlate concentrations and intake with proposal ids
      result <- rstan::extract(intake_model)
     
      # Add inference details
      intake_proposals.df <- data.frame(proposal=1:dim(result$Y_mu)[1])
      intake_proposals.df$lp <- result$lp__
      intake_proposals.df$preference <- result$preference_lpdf
      intake_proposals.df$in_concentration_range <- result$in_concentration_range_lpdf
      intake_proposals.df$boundsum <- result$softbound_sum
      intake_proposals.df$in_range <- result$in_range

      contributions.df <- data.frame()
      
      # Add expected values of concentrations
      for (node_index in 1:nrow(assumedtargets)) {
        node_name <- assumedtargets[node_index,]$Name
        conc_mu_distribution <- result$Y_mu[,node_index]
        intake_proposals.df <- cbind(intake_proposals.df, conc_mu_distribution)
        
        # Extract and store contributions of nutrients on concentrations
        temp.df <- data.frame(queried_nodes)
        temp.df$concentration <- node_name
        temp.df$contributions <- colMeans(result$Q_contributions[,node_index,])
        temp.df <- rbind(temp.df, c("base", node_name, head(result$Y_mu_Q0[,node_index],1)))
        contributions.df <- rbind(contributions.df, temp.df)
      }

      saveRDS(contributions.df, paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/details/contributions_",graph_person_id,".rds"))
      
      # Add related intake proposals
      for (node_index in 1:length(queried_nodes)) {
        node_name <- queried_nodes[[node_index]]
        Q_proposal <- result$Q[,node_index] * org_stats[org_stats$name == node_name,]$sd + org_stats[org_stats$name == node_name,]$mean
        intake_proposals.df <- cbind(intake_proposals.df, Q_proposal)
      }
      
      colnames(intake_proposals.df) <- c("proposal", "lp", "preference", "in_concentration_range", "boundsum", "in_range", assumedtargets$Name, queried_nodes)
      
      saveRDS(intake_proposals.df %>% as.data.frame(), paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/details/accepted_intake_",graph_person_id,".rds"))
      
      # Filter recommendation distributions
      recommendation_intake.df <- intake_proposals.df %>%
        filter(boundsum >= 2 * nrow(assumedtargets) - 0.5) %>%
        as.data.frame()
    
      saveRDS(recommendation_intake.df %>% as.data.frame(), paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/details/recommendation_intake_",graph_person_id,".rds"))
          
      print(paste0("Number of recommendation sample size ", nrow(recommendation_intake.df)))
      
      if (nrow(recommendation_intake.df) > 0)
      {
          RI_mean <- colMeans(recommendation_intake.df[queried_nodes])
          RI_quantiles <- lapply(recommendation_intake.df[queried_nodes], quantile, probs = c(0.025,0.975))
          RI_lower_quantiles <- as.vector(unlist(RI_quantiles)[seq(1, length(queried_nodes)*2, by = 2)])
          RI_upper_quantiles <- as.vector(unlist(RI_quantiles)[seq(2, length(queried_nodes)*2, by = 2)])
          
          personal_intake <- c(graph_person_id,
                               as.character(subject_code),
                               1,
                               RI_mean,
                               RI_lower_quantiles,
                               RI_upper_quantiles,
                               mean(recommendation_intake.df$fshdl),
                               mean(recommendation_intake.df$fsldl),
                               mean(recommendation_intake.df$fsins),
                               mean(recommendation_intake.df$fskol),
                               mean(recommendation_intake.df$fpgluk),
                               apply(result$Y_bound[,seq(1, nrow(assumedtargets))], MARGIN=c(2), max),
                               apply(result$Y_bound[,2*seq(1, nrow(assumedtargets))], MARGIN=c(2), max)
                               )
      } 
      else
      {
         personal_intake <- c(graph_person_id,
                              as.character(subject_code),
                              0,
                              rep(0,length(queried_nodes) * 3),
                              mean(intake_proposals.df$fshdl),
                              mean(intake_proposals.df$fsldl),
                              mean(intake_proposals.df$fsins),
                              mean(intake_proposals.df$fskol),
                              mean(intake_proposals.df$fpgluk),
                              apply(result$Y_bound[,seq(1, nrow(assumedtargets))], MARGIN=c(2), max),
                              apply(result$Y_bound[,2*seq(1, nrow(assumedtargets))], MARGIN=c(2), max)
                              )
      }
    
      patient_summary <- rbind(patient_summary, personal_intake)
    }
}

colnames(patient_summary) <- c("person_id", "subject_code", "accepted", paste0(queried_nodes), paste0(queried_nodes, "_lCI"), paste0(queried_nodes, "_uCI"), assumedtargets$Name, paste0(assumedtargets$Name, "_lowerbound"), paste0(assumedtargets$Name, "_upperbound"))

saveRDS(patient_summary, paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary.rds"))

# As a result, we have proposal distributions of nutrients. Next, we predict concentrations that are produced by expected values of those proposal distributions.

```


```{r}

ggplot(data=recommendation_intake.df[order(-recommendation_intake.df$proposal),]) +
  geom_line(aes(y=proposal, x=cvit, color=preference)) 

```


```{r fig.height=8, inference_debug}

fshdl_recommendations <- c(recommeded_concentrations$lower_limits[1], recommeded_concentrations$upper_limits[1])
fsldl_recommendations <- c(recommeded_concentrations$lower_limits[2], recommeded_concentrations$upper_limits[2])
fsins_recommendations <- c(recommeded_concentrations$lower_limits[3], recommeded_concentrations$upper_limits[3])
fskol_recommendations <- c(recommeded_concentrations$lower_limits[4], recommeded_concentrations$upper_limits[4])
fpgluk_recommendations <- c(recommeded_concentrations$lower_limits[5], recommeded_concentrations$upper_limits[5])

recommendation_intake.df <- intake_proposals.df 

#recommendation_intake.df <- intake_proposals.df %>%
#  filter(boundsum >= 2 * nrow(assumedtargets) - 0.3) %>%
#  as.data.frame()

conc_plot1 <- ggplot(recommendation_intake.df) +
  geom_point(aes(y=lp, x=fshdl, color=preference), show.legend=FALSE) +
  #geom_density(aes(x=fshdl), color="darkblue", fill="lightblue") +
  geom_vline(xintercept = mean(recommendation_intake.df$fshdl), linetype="dashed", color = "black", linewidth=0.4) +
  geom_vline(xintercept = fshdl_recommendations, linetype="solid", color = "black", linewidth=0.4) +
  scale_color_gradientn(colours = colorspace::diverge_hcl(7)) 

conc_plot2 <- ggplot(recommendation_intake.df) +
  geom_point(aes(y=lp, x=fsldl, color=preference), show.legend=FALSE) +
  #geom_density(aes(x=fsldl), color="darkblue", fill="lightblue") +
  geom_vline(xintercept = mean(recommendation_intake.df$fsldl), linetype="dashed", color = "black", linewidth=0.4) +
  geom_vline(xintercept = fsldl_recommendations, linetype="solid", color = "black", linewidth=0.4) +
  scale_color_gradientn(colours = colorspace::diverge_hcl(7))

conc_plot3 <- ggplot(recommendation_intake.df) +
  geom_point(aes(y=lp, x=fsins, color=preference), show.legend=FALSE) +
  #geom_density(aes(x=fsins), color="darkblue", fill="lightblue") +
  geom_vline(xintercept = mean(recommendation_intake.df$fsins), linetype="dashed", color = "black", linewidth=0.4) +
  geom_vline(xintercept = fsins_recommendations, linetype="solid", color = "black", linewidth=0.4) +
  scale_color_gradientn(colours = colorspace::diverge_hcl(7))

conc_plot4 <- ggplot(recommendation_intake.df) +
  geom_point(aes(y=lp, x=fskol, color=preference), show.legend=FALSE) +
  #geom_density(aes(x=fskol), color="darkblue", fill="lightblue") +
  geom_vline(xintercept = mean(recommendation_intake.df$fskol), linetype="dashed", color = "black", linewidth=0.4) +
  geom_vline(xintercept = fskol_recommendations, linetype="solid", color = "black", linewidth=0.4) +
  scale_color_gradientn(colours = colorspace::diverge_hcl(7))

conc_plot5 <- ggplot(recommendation_intake.df) +
  geom_point(aes(y=lp, x=fpgluk, color=preference), show.legend=FALSE) +
  #geom_density(aes(x=fpgluk), color="darkblue", fill="lightblue") +
  geom_vline(xintercept = mean(recommendation_intake.df$fpgluk), linetype="dashed", color = "black", linewidth=0.4) +
  geom_vline(xintercept = fpgluk_recommendations, linetype="solid", color = "black", linewidth=0.4) +
  scale_color_gradientn(colours = colorspace::diverge_hcl(7))
  
lay <- rbind(c(1),
             c(2),
             c(3),
             c(4),
             c(5))

lp_plot <- grid.arrange(conc_plot1, conc_plot2, conc_plot3, conc_plot4, conc_plot5, layout_matrix = lay, padding=0)

```

```{r current_levels_and_effect_summary}
# Add current levels of intake and concentrations to the data frame
library(stringr)
library(igraph)
library(dplyr)

datadesc <- sysdimet_datadesc
queried_nodes <- as.vector(datadesc[datadesc$Condition >= 100,]$Name)

simulation <- "X50_B50_A50_I50"

# - current levels are joined with this summary
recommendation_with_concpreds.df <- readRDS(paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary.rds"))

current_diet.df <- data.frame(matrix(ncol = 1 + length(queried_nodes) + nrow(sysdimet_targets), nrow = 0), row.names = NULL)

personal_effects <- data.frame()

for (subject_code in recommendation_with_concpreds.df$subject_code) {
  
  effects <- vector()
  effect_names <- vector()

  graph_person_id <- match(subject_code, levels(sysdimet$SUBJECT_ID))

  graph_dir <- paste0("graphs/sysdimet/gamma_qr_mv/",graph_person_id)
  print(graph_dir)
  
  personal_graph <- read.graph(paste0(graph_dir, "/personal_graph.graphml"), "graphml")
  nodes <- V(personal_graph)

  # Current intake levels
  
  current_intake <- c()
  intake_nodes <- V(personal_graph)[queried_nodes]
  
  for (i in 1:length(queried_nodes))
  {
    current_dist <- intake_nodes[i]$distribution
    
    current_intake_level <- 0
    if (startsWith(current_dist, "N"))
    {
        # get current intake from mean of intake normal distribution
        current_intake_level <- as.numeric(str_extract(current_dist, "(?<=N\\().+(?=,)")) # N(*,
    }
  
    current_intake <- c(current_intake, current_intake_level)
    
    # collect personal effects statistics
    for (t in sysdimet_targets$Name)
    {
      effect_name <- paste0(queried_nodes[i],"_",t)
      
      effects <-  c(graph_person_id,
                    effect_name,
                    nodes[paste0("personal_", effect_name)]$value,
                    nodes[paste0("personal_", effect_name)]$value_lCI,
                    nodes[paste0("personal_", effect_name)]$value_uCI)
      
      personal_effects <- rbind(personal_effects, effects)
    }
  }
  
  # Current concentration levels

  current_concs <- c()
  conc_nodes <- V(personal_graph)[sysdimet_targets$Name]
  
  for (i in 1:length(conc_nodes))
  {
    current_conc_level <- conc_nodes[i]$value_mean
    current_concs <- c(current_concs, current_conc_level)
  }
  
  current_diet.df <- rbind(current_diet.df, c(as.character(graph_person_id), current_intake, current_concs))
}

colnames(personal_effects) <- c("graph_person_id", "effect", "value", "value_lCI", "value_uCI")

colnames(current_diet.df) <- c("person_id", paste0("current_", queried_nodes), paste0("current_", sysdimet_targets$Name))

# Join recommendations with current situation

recommendation_with_concpreds.df$person_id <- as.integer(recommendation_with_concpreds.df$person_id)
#recommendation_with_concpreds.df$subject_code <- gsub("S", "", recommendation_with_concpreds.df$subject_code)

current_diet.df <- as.data.frame(sapply(current_diet.df, as.numeric))
current_diet.df$person_id <- as.integer(current_diet.df$person_id)

recommendation_with_concpreds_and_current.df <- recommendation_with_concpreds.df %>% inner_join(current_diet.df, by="person_id")

# - Remove S from subject code
recommendation_with_concpreds_and_current.df$subject_code <- gsub("S","",recommendation_with_concpreds_and_current.df$subject_code)

# Convert all columns as numerics
recommendation_with_concpreds_and_current.df <- as.data.frame(sapply(recommendation_with_concpreds_and_current.df, as.numeric))

saveRDS(recommendation_with_concpreds_and_current.df, paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary_with_concpreds_and_current.rds"))

```

```{r}
effect_summary <- personal_effects %>% 
  group_by(effect) %>%
  dplyr::summarise(
                effect_avg = mean(as.numeric(value)),
                effect_sd = sd(as.numeric(value)),                 
                min_personal = min(as.numeric(value)),
                min_personal_lCI = as.numeric(value_lCI[which.min(as.numeric(value))]),
                min_personal_uCI = as.numeric(value_uCI[which.min(as.numeric(value))]),
                max_personal = max(as.numeric(value)),
                max_personal_lCI = as.numeric(value_lCI[which.max(as.numeric(value))]),
                max_personal_uCI = as.numeric(value_uCI[which.max(as.numeric(value))])
  ) %>%
  arrange(desc(abs(effect_avg)))

#effect_summary[effect_summary$effect=="cvit_fsins",]

#effect_summary
```


```{r}
library(kableExtra) # for HTML and Latex tables

# personal_effects is gathered in the previous block

effect_summary <- personal_effects %>% 
  group_by(effect) %>%
  dplyr::summarise(
                effect_avg = mean(as.numeric(value)),
                effect_sd = sd(as.numeric(value)),                 
                min_personal = min(as.numeric(value)),
                min_personal_lCI = as.numeric(value_lCI[which.min(as.numeric(value))]),
                min_personal_uCI = as.numeric(value_uCI[which.min(as.numeric(value))]),
                max_personal = max(as.numeric(value)),
                max_personal_lCI = as.numeric(value_lCI[which.max(as.numeric(value))]),
                max_personal_uCI = as.numeric(value_uCI[which.max(as.numeric(value))])
  ) %>%
  arrange(desc(abs(effect_avg))) %>%
  top_n(100)

effect_summary_table.df <- data.frame(effect <- effect_summary$effect, row.names = NULL)

effect_summary_table.df$effect_avg <- linebreak(paste0(format(round(effect_summary$effect_avg,2), nsmall=2)))
effect_summary_table.df$effect_sd <- linebreak(paste0(format(round(effect_summary$effect_sd,2), nsmall=2)))

effect_summary_table.df$min_personal <- linebreak(paste0(format(round(effect_summary$min_personal,2), nsmall=2),"\n$\\left[",format(round(effect_summary$min_personal_lCI,2), nsmall=2),"; ",format(round(effect_summary$min_personal_uCI,2), nsmall=2),"\\right]$"), align = "c")

effect_summary_table.df$max_personal <- linebreak(paste0(format(round(effect_summary$max_personal,2), nsmall=2),"\n$\\left[",format(round(effect_summary$max_personal_lCI,2), nsmall=2),"; ",format(round(effect_summary$max_personal_uCI,2), nsmall=2),"\\right]$"), align = "c")

colnames(effect_summary_table.df) <- c("effect", "effect_avg", "effect_sd", "min_personal", "max_personal")

# lookup dataframe for pretty effect names
all_effects <- expand.grid(predictor = sysdimet_predictors$Name, target = sysdimet_targets$Name)
all_descs <- expand.grid(predictor = sysdimet_predictors$ShortDescription, target = sysdimet_targets$ShortDescription)
effect_desc.df <- data.frame(effect <- paste0(all_effects$predictor,"_",all_effects$target), row.names = NULL)
effect_desc.df$desc <- paste0(effect <- paste0(all_descs$predictor," -> ",all_descs$target))
effect_desc.df$nutrient <- all_descs$predictor
effect_desc.df$concentration <- all_descs$target
colnames(effect_desc.df) <- c("effect", "effect_description", "nutrient", "concentration")

effect_summary_table.df <- effect_summary_table.df %>% left_join(effect_desc.df, by = "effect")

kable(effect_summary_table.df[c(6,2:5)], "html", escape = F, booktabs = T, row.names = FALSE, digits = 2,align="lccccccccccc",
  col.names = c("Effect", "Avg. effect", "Effect sd.", "Min. personal effect", "Max personal effect")) %>%
  column_spec(1, width = "7em") %>%
  kable_styling(latex_options="scale_down") %>%  
  kable_styling(latex_options = c("basic", "condensed"), full_width = TRUE) %>%
  row_spec(0,bold=TRUE)# %>%
#  save_kable(file = "tables/sysdimet_effects.pdf", keep_tex = TRUE)

```


#sysdimet_lp_plots
```{r sysdimet_lp_plots-function}

sysdimet_lp_plots <- function(subject_code_vector, plot_path) {
  
  library(ggplot2)
  library(gridExtra)
  
  persons <- length(subject_code_vector)
  
  concinfo.df <- readRDS(paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary_with_concpreds_and_current.rds"))
  
  simulation <- "X50_B50_A50_I50"
  conc_plots <- vector('list', persons)
  
  fshdl_scale_min <- min(0.8, concinfo.df$current_fshdl[1:persons])-0.1
  fshdl_scale_max <- max(2.7, concinfo.df$current_fshdl[1:persons])+0.1
  fsldl_scale_min <- min(1.2, concinfo.df$current_fsldl[1:persons])-0.1
  fsldl_scale_max <- max(5.3, concinfo.df$current_fsldl[1:persons])+0.1
  fsins_scale_min <- min(2.6, concinfo.df$current_fsins[1:persons])-0.1
  fsins_scale_max <- max(25.0, concinfo.df$current_fsins[1:persons])+0.1
  fskol_scale_min <- min(2.9, concinfo.df$current_fskol[1:persons])-0.1
  fskol_scale_max <- max(7.8, concinfo.df$current_fskol[1:persons])+0.1
  fpgluk_scale_min <- min(4.0, concinfo.df$current_fpgluk[1:persons])-0.1
  fpgluk_scale_max <- max(6.0, concinfo.df$current_fpgluk[1:persons])+0.1
  
  point_size <- 0.5
  
  #normal_palette <- c("#00337C", "#AADDFF", "#DDFFFF", "#03C988")
  #failed_palette <- c("#00337C", "#DDDDDD", "#FFDDDD", "#FF6961")

  normal_palette <- "#00BFFF"
  failed_palette <- "#FFAADD"
  mid_color <- "#FFFFFF"
  low_color <- "#F44336"

  gradient_colors <- colorspace::heat_hcl(3)
  plot_index <- 1
  
  for (subject_code in subject_code_vector[1:(persons-1)]) {
    
      person_id <- concinfo.df[concinfo.df$subject_code == subject_code,]$person_id
      
      #print(subject_code)
      
      rec_file <- paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/details/accepted_intake_",person_id,".rds")
      
      if (file.exists(rec_file)) {
        
        accepted_intake.df <- readRDS(rec_file)
    
        # Get personal normal ranges
        subject_id <- sprintf("S%02d", subject_code)
        personal_info <- sysdimet[sysdimet$SUBJECT_ID == subject_id & sysdimet$WEEK == 0,]
        
        recommeded_concentrations <- mebn.get_personal_sysdimet_guidelines(personal_info)
        
        fshdl_recommendations <- c(recommeded_concentrations$lower_limits[1], recommeded_concentrations$upper_limits[1])
        fsldl_recommendations <- c(recommeded_concentrations$lower_limits[2], recommeded_concentrations$upper_limits[2])
        fsins_recommendations <- c(recommeded_concentrations$lower_limits[3], recommeded_concentrations$upper_limits[3])
        fskol_recommendations <- c(recommeded_concentrations$lower_limits[4], recommeded_concentrations$upper_limits[4])
        fpgluk_recommendations <- c(recommeded_concentrations$lower_limits[5], recommeded_concentrations$upper_limits[5])
        
        # Get current personal info and predictions
      
        curr_fshdl <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fshdl
        curr_fsldl <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fsldl
        curr_fsins <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fsins
        curr_fskol <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fskol
        curr_fpgluk <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fpgluk
    
        pred_fshdl <- concinfo.df[concinfo.df$subject_code == subject_code,]$fshdl
        pred_fsldl <- concinfo.df[concinfo.df$subject_code == subject_code,]$fsldl
        pred_fsins <- concinfo.df[concinfo.df$subject_code == subject_code,]$fsins
        pred_fskol <- concinfo.df[concinfo.df$subject_code == subject_code,]$fskol
        pred_fpgluk <- concinfo.df[concinfo.df$subject_code == subject_code,]$fpgluk
        
        lp_midpoint <- mean(accepted_intake.df$lp)
        
        conc_plot1 <- ggplot(accepted_intake.df) +
          geom_point(aes(y=lp, x=fshdl, color=preference), size = point_size, show.legend = FALSE) +
          #geom_vline(xintercept = fshdl_recommendations, linetype="solid", color = "black", linewidth=0.2) +
          geom_vline(xintercept = pred_fshdl, linetype="solid", color = "black", linewidth=0.3) +
          geom_vline(xintercept = curr_fshdl, linetype="dashed", color = "black", linewidth=0.3) +
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fshdl_recommendations[1], alpha = .2) + 
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=fshdl_recommendations[2], xmax=Inf, alpha = .2) + 
          scale_x_continuous(limits=c(fshdl_scale_min, fshdl_scale_max), breaks=fshdl_recommendations) +
          #scale_colour_gradient2(low=low_color, high=if (fshdl_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
          scale_color_gradientn(colours = gradient_colors) +
          theme_bw() +
          theme(panel.grid.minor = element_blank()) +
          #theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
          #theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
          #labs(x = element_blank(), y = subject_code) +
          labs(x = element_blank(), y = paste0(subject_code, " ", "\nlog-prob."))
  
        conc_plot2 <- ggplot(accepted_intake.df) +
          geom_point(aes(y=lp, x=fsldl, color=preference), size = point_size, show.legend = FALSE) +
          #geom_vline(xintercept = fsldl_recommendations, linetype="solid", color = "black", linewidth=0.2) +
          geom_vline(xintercept = pred_fsldl, linetype="solid", color = "black", linewidth=0.3) +
          geom_vline(xintercept = curr_fsldl, linetype="dashed", color = "black", linewidth=0.3) +
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fsldl_recommendations[1], alpha = .2) + 
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=fsldl_recommendations[2], xmax=Inf, alpha = .2) + 
          scale_x_continuous(limits=c(fsldl_scale_min, fsldl_scale_max), breaks=fsldl_recommendations) +
          #scale_colour_gradient2(low=low_color,mid=mid_color, high=if (fsldl_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
          scale_color_gradientn(colours = gradient_colors) +
          theme_bw() +
          theme(panel.grid.minor = element_blank()) +
          theme(axis.text.y = element_blank()) +
          labs(x = element_blank(), y = element_blank())
    
        conc_plot3 <- ggplot(accepted_intake.df) +
          geom_point(aes(y=lp, x=fsins, color=preference), size = point_size, show.legend = FALSE) +
          #geom_vline(xintercept = fsins_recommendations, linetype="solid", color = "black", linewidth=0.4) +
          geom_vline(xintercept = pred_fsins, linetype="solid", color = "black", linewidth=0.3) +
          geom_vline(xintercept = curr_fsins, linetype="dashed", color = "black", linewidth=0.3) +
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fsins_recommendations[1], alpha = .2) + 
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=fsins_recommendations[2], xmax=Inf, alpha = .2) + 
          scale_x_continuous(limits=c(fsins_scale_min, fsins_scale_max), breaks=fsins_recommendations) +
          #scale_colour_gradient2(low=low_color, high=if (fsins_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
          #scale_color_gradientn(colours = colorspace::diverge_hcl(7)) +
          scale_color_gradientn(colours = gradient_colors) +
          theme_bw() +
          theme(panel.grid.minor = element_blank()) +
          theme(axis.text.y = element_blank()) +
          labs(x = element_blank(), y = element_blank())
    
        conc_plot4 <- ggplot(accepted_intake.df) +
          geom_point(aes(y=lp, x=fskol, color=preference), size = point_size, show.legend = FALSE) +
          #geom_vline(xintercept = fskol_recommendations, linetype="solid", color = "black", linewidth=0.4) +
          geom_vline(xintercept = pred_fskol, linetype="solid", color = "black", linewidth=0.3) +
          geom_vline(xintercept = curr_fskol, linetype="dashed", color = "black", linewidth=0.3) +
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fskol_recommendations[1], alpha = .2) + 
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=fskol_recommendations[2], xmax=Inf, alpha = .2) + 
          scale_x_continuous(limits=c(fskol_scale_min, fskol_scale_max), breaks=fskol_recommendations) +
          #scale_colour_gradient2(low=low_color, high=if (fskol_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
          scale_color_gradientn(colours = gradient_colors) +
          theme_bw() +
          theme(panel.grid.minor = element_blank()) +
          theme(axis.text.y = element_blank()) +
          labs(x = element_blank(), y = element_blank())
    
        conc_plot5 <- ggplot(accepted_intake.df) +
          geom_point(aes(y=lp, x=fpgluk, color=preference), size = point_size, show.legend = FALSE) +
          #geom_vline(xintercept = fpgluk_recommendations, linetype="solid", color = "black", linewidth=0.4) +
          geom_vline(xintercept = pred_fpgluk, linetype="solid", color = "black", linewidth=0.3) +
          geom_vline(xintercept = curr_fpgluk, linetype="dashed", color = "black", linewidth=0.3) +
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fpgluk_recommendations[1], alpha = .2) + 
          annotate("rect",ymin=-Inf, ymax=Inf, xmin=fpgluk_recommendations[2], xmax=Inf, alpha = .2) + 
          scale_x_continuous(limits=c(fpgluk_scale_min, fpgluk_scale_max), breaks=fpgluk_recommendations) +
          #scale_colour_gradient2(low=low_color, high=if (fpgluk_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
          scale_color_gradientn(colours = gradient_colors) +
          theme_bw() +
          theme(panel.grid.minor = element_blank()) +
          theme(axis.text.y = element_blank()) +
          labs(x = element_blank(), y = element_blank())
        
        conc_plot <- grid.arrange(conc_plot1, conc_plot2, conc_plot3, conc_plot4, conc_plot5, ncol=5, padding=0, widths=c(1.4,1,1,1,1))
        
        conc_plots[[plot_index]] <- conc_plot
        plot_index <- plot_index + 1

        subject_code <- subject_code_vector[[persons]]
        person_id <- concinfo.df[concinfo.df$subject_code == subject_code,]$person_id
    }
    
    rec_file <- paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/details/accepted_intake_",person_id,".rds")
      
    if (file.exists(rec_file)) {

      accepted_intake.df <- readRDS(rec_file)
      
      # Get personal normal ranges
      subject_id <- sprintf("S%02d", subject_code)
      
      personal_info <- sysdimet[sysdimet$SUBJECT_ID == subject_id & sysdimet$WEEK == 0,]
      recommeded_concentrations <- mebn.get_personal_sysdimet_guidelines(personal_info)
      
      fshdl_recommendations <- c(recommeded_concentrations$lower_limits[1], recommeded_concentrations$upper_limits[1])
      fsldl_recommendations <- c(recommeded_concentrations$lower_limits[2], recommeded_concentrations$upper_limits[2])
      fsins_recommendations <- c(recommeded_concentrations$lower_limits[3], recommeded_concentrations$upper_limits[3])
      fskol_recommendations <- c(recommeded_concentrations$lower_limits[4], recommeded_concentrations$upper_limits[4])
      fpgluk_recommendations <- c(recommeded_concentrations$lower_limits[5], recommeded_concentrations$upper_limits[5])
      
      # Get current personal info and predictions
      
      curr_fshdl <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fshdl
      curr_fsldl <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fsldl
      curr_fsins <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fsins
      curr_fskol <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fskol
      curr_fpgluk <- concinfo.df[concinfo.df$subject_code == subject_code,]$current_fpgluk
      
      pred_fshdl <- concinfo.df[concinfo.df$subject_code == subject_code,]$fshdl
      pred_fsldl <- concinfo.df[concinfo.df$subject_code == subject_code,]$fsldl
      pred_fsins <- concinfo.df[concinfo.df$subject_code == subject_code,]$fsins
      pred_fskol <- concinfo.df[concinfo.df$subject_code == subject_code,]$fskol
      pred_fpgluk <- concinfo.df[concinfo.df$subject_code == subject_code,]$fpgluk
    
      lp_midpoint <- mean(accepted_intake.df$lp) * 0.50
    
      conc_plot1 <- ggplot(accepted_intake.df) +
        geom_point(aes(y=lp, x=fshdl, color=preference), size = point_size, show.legend = FALSE) +
        #geom_vline(xintercept = fshdl_recommendations, linetype="solid", color = "black", linewidth=0.2) +
        geom_vline(xintercept = pred_fshdl, linetype="solid", color = "black", linewidth=0.3) +
        geom_vline(xintercept = curr_fshdl, linetype="dashed", color = "black", linewidth=0.3) +
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fshdl_recommendations[1], alpha = .2) + 
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=fshdl_recommendations[2], xmax=Inf, alpha = .2) + 
        scale_x_continuous(limits=c(fshdl_scale_min, fshdl_scale_max), breaks=fshdl_recommendations) +
        #scale_colour_gradient2(low=low_color, high=if (fshdl_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
        scale_color_gradientn(colours = gradient_colors) +
        theme_bw() +
        theme(panel.grid.minor = element_blank()) +
        labs(x = "fS-HDL (mmol/l)", y = paste0(subject_code, " ", "\nlog-prob."))
      
      conc_plot2 <- ggplot(accepted_intake.df) +
        geom_point(aes(y=lp, x=fsldl, color=preference), size = point_size, show.legend = FALSE) +
        #geom_vline(xintercept = fsldl_recommendations, linetype="solid", color = "black", linewidth=0.2) +
        geom_vline(xintercept = pred_fsldl, linetype="solid", color = "black", linewidth=0.3) +
        geom_vline(xintercept = curr_fsldl, linetype="dashed", color = "black", linewidth=0.3) +
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fsldl_recommendations[1], alpha = .2) + 
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=fsldl_recommendations[2], xmax=Inf, alpha = .2) + 
        scale_x_continuous(limits=c(fsldl_scale_min, fsldl_scale_max), breaks=fsldl_recommendations) +
        #scale_colour_gradient2(low=low_color, high=if (fsldl_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
        scale_color_gradientn(colours = gradient_colors) +
        theme_bw() +
        theme(panel.grid.minor = element_blank()) +
        theme(axis.text.y = element_blank()) +
        labs(x = "fS-LDL (mmol/l)", y = element_blank())
      
      conc_plot3 <- ggplot(accepted_intake.df) +
        geom_point(aes(y=lp, x=fsins, color=preference), size = point_size, show.legend = FALSE) +
        #geom_vline(xintercept = fsins_recommendations, linetype="solid", color = "black", linewidth=0.4) +
        geom_vline(xintercept = pred_fsins, linetype="solid", color = "black", linewidth=0.3) +
        geom_vline(xintercept = curr_fsins, linetype="dashed", color = "black", linewidth=0.3) +
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fsins_recommendations[1], alpha = .2) + 
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=fsins_recommendations[2], xmax=Inf, alpha = .2) + 
        scale_x_continuous(limits=c(fsins_scale_min, fsins_scale_max), breaks=fsins_recommendations) +
        #scale_colour_gradient2(low=low_color, high=if (fsins_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
        scale_color_gradientn(colours = gradient_colors) +
        theme_bw() +
        theme(panel.grid.minor = element_blank()) +
        theme(axis.text.y = element_blank()) +
        labs(x = "fS-Ins (mmol/l)", y = element_blank())
      
      conc_plot4 <- ggplot(accepted_intake.df) +
        geom_point(aes(y=lp, x=fskol, color=preference), size = point_size, show.legend = FALSE) +
        #geom_vline(xintercept = fskol_recommendations, linetype="solid", color = "black", linewidth=0.4) +
        geom_vline(xintercept = pred_fskol, linetype="solid", color = "black", linewidth=0.3) +
        geom_vline(xintercept = curr_fskol, linetype="dashed", color = "black", linewidth=0.3) +
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fskol_recommendations[1], alpha = .2) + 
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=fskol_recommendations[2], xmax=Inf, alpha = .2) + 
        scale_x_continuous(limits=c(fskol_scale_min, fskol_scale_max), breaks=fskol_recommendations) +
        #scale_colour_gradient2(low=low_color, high=if (fskol_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
        scale_color_gradientn(colours = gradient_colors) +
        theme_bw() +
        theme(panel.grid.minor = element_blank()) +
        theme(axis.text.y = element_blank()) +
        labs(x = "fS-Chol (mmol/l)", y = element_blank())
      
      conc_plot5 <- ggplot(accepted_intake.df) +
        geom_point(aes(y=lp, x=fpgluk, color=preference), size = point_size, show.legend = FALSE) +
        #geom_vline(xintercept = fpgluk_recommendations, linetype="solid", color = "black", linewidth=0.4) +
        geom_vline(xintercept = pred_fpgluk, linetype="solid", color = "black", linewidth=0.3) +
        geom_vline(xintercept = curr_fpgluk, linetype="dashed", color = "black", linewidth=0.3) +
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fpgluk_recommendations[1], alpha = .2) + 
        annotate("rect",ymin=-Inf, ymax=Inf, xmin=fpgluk_recommendations[2], xmax=Inf, alpha = .2) + 
        scale_x_continuous(limits=c(fpgluk_scale_min, fpgluk_scale_max), breaks=fpgluk_recommendations) +
        #scale_colour_gradient2(low=low_color, high=if (fpgluk_accepted) normal_palette else failed_palette, midpoint=lp_midpoint) +
        scale_color_gradientn(colours = gradient_colors) +
        theme_bw() +
        theme(panel.grid.minor = element_blank()) +
        theme(axis.text.y = element_blank()) +
        labs(x = "fP-Gluc (mmol/l)", y = element_blank())
      
      conc_plot <- grid.arrange(conc_plot1, conc_plot2, conc_plot3, conc_plot4, conc_plot5, ncol=5, padding=0, widths=c(1.4,1,1,1,1))
      
      conc_plots[[plot_index]] <- conc_plot
    } # if recommendation exists
  } # for all
  
  full_conc_plot <- grid.arrange(grobs = conc_plots, ncol=1, padding=0, heights=c(rep(1, plot_index-1),1.1))
  #full_conc_plot <- grid.arrange(grobs = conc_plots, ncol=1, padding=0)
  
  ggsave(plot_path, plot = full_conc_plot)
}

```

#sysdimet_lp_article_plot

```{r sysdimet_lp_article_plot, cache=FALSE, eval=TRUE, echo=FALSE,message=FALSE, warning=FALSE, fig.width=7, fig.height=6, fig.keep='last'}

# Only patients with non-optimal concentrations are included in the recommendation

subjects_with_failed_concs <- readRDS(paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary_with_concpreds_and_current.rds"))

sysdimet_lp_plots(subjects_with_failed_concs[1:10,]$subject_code, "figures/sysdimet_fixed_concentrations.pdf")
#sysdimet_lp_plots(subjects_with_failed_concs$subject_code, "figures/sysdimet_fixed_concentrations_all.pdf")

```

# Intake recommendation

```{r result_plot_for_all_in_kontrolli_change}

# Visualize the main results
library(tibble)
library(dplyr)

intake.df <- readRDS(paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary_with_concpreds_and_current.rds"))

recommendation <- colnames(intake.df)[4:(4+14)]

#columns_with_icons <- c("person_id", (rbind(paste0(recommendation, "_icon"), recommendation)))

cond_nutrients <- sysdimet_predictors[sysdimet_predictors$Condition >= 100,]
table_colnames <- c("", cond_nutrients$ShortDescription)

up_color <- "#C23B22"
down_color <- "#00BFC4"
down_color <- "#3A5874"
keep_color <- "#000000"
  
recommendation_table.df <- intake.df %>%
                              # Recommendation cell coloring conditional on difference from current value
                              mutate(across(.cols = recommendation,
                                            .fns = ~case_when(
                                               get(glue::glue("current_{cur_column()}")) <= .x ~ up_color,
                                               get(glue::glue("current_{cur_column()}"))  > .x ~ down_color,
                                               get(glue::glue("current_{cur_column()}"))  == .x ~ keep_color,
                                            ),
                                            .names = "{.col}_color")) %>%
                              # Cell bolding conditional on amount of the difference (30%)
                              mutate(across(.cols = recommendation,
                                            .fns = ~case_when(
                                               abs(((get(glue::glue("current_{cur_column()}"))) - .x) / .x * 100) >= 30 ~ TRUE,
                                               abs(((get(glue::glue("current_{cur_column()}"))) - .x) / .x * 100) < 30 ~ FALSE,
                                               .default = FALSE,
                                            ),
                                            .names = "{.col}_bold")) %>%
                              # Round, format and paste as multiline-string with CI
                              mutate(across(.cols = all_of(recommendation),
                                            .fns = ~linebreak(paste0(
                                              "${_{",
                                              format(round(get(glue::glue("current_{cur_column()}")), cond_nutrients[cond_nutrients$Name == {cur_column()},]$Decimals), 
                                                     nsmall = cond_nutrients[cond_nutrients$Name == {cur_column()},]$Decimals),
                                              "\\rightarrow}}$ \n",
                                              format(round(.x, cond_nutrients[cond_nutrients$Name == {cur_column()},]$Decimals), 
                                                     nsmall = cond_nutrients[cond_nutrients$Name == {cur_column()},]$Decimals),
                                              "\n${^{\\left[",
                                              format(round(get(glue::glue("{cur_column()}_lCI")), cond_nutrients[cond_nutrients$Name == {cur_column()},]$Decimals), 
                                                     nsmall = cond_nutrients[cond_nutrients$Name == {cur_column()},]$Decimals),
                                              "; ", 
                                              format(round(get(glue::glue("{cur_column()}_uCI")), cond_nutrients[cond_nutrients$Name == {cur_column()},]$Decimals), 
                                                    nsmall = cond_nutrients[cond_nutrients$Name == {cur_column()},]$Decimals), 
                                              "\\right]}}$"), 
                                              align="c"),
                                            .names = "{.col}")) %>%
                              select(c("subject_code", recommendation, paste0(recommendation,"_color"), paste0(recommendation,"_bold"), "subject_code"))

# Render PDF table and keep .tex 

fixed_concs.df <- recommendation_table.df[recommendation_table.df$subject_code %in% subjects_with_failed_concs$subject_code,]

kable(fixed_concs.df[1:16], format = "latex", escape = F, booktabs = T, row.names = FALSE, align = c("r", rep("c",16)), 
   col.names = table_colnames,
   caption = "Personal intake recommendations for Sysdimet study control cohort with the current intake, recommendation most fitting to model, and 90\\%-probability range of recommendations.") %>%
    kable_styling(latex_options="scale_down") %>%  
    kable_styling(latex_options = c("basic", "condensed"), full_width = TRUE) %>%
   row_spec(0,bold=TRUE) %>%
   column_spec(1, color = "#000000") %>%
   column_spec(2, color = fixed_concs.df[,17], bold = fixed_concs.df[,32], underline = fixed_concs.df[,17] == FALSE) %>%
   column_spec(3, color = fixed_concs.df[,18], bold = fixed_concs.df[,33], underline = fixed_concs.df[,18] == FALSE) %>%
   column_spec(4, color = fixed_concs.df[,19], bold = fixed_concs.df[,34], underline = fixed_concs.df[,19] == FALSE) %>%
   column_spec(5, color = fixed_concs.df[,20], bold = fixed_concs.df[,35], underline = fixed_concs.df[,20] == FALSE) %>%
   column_spec(6, color = fixed_concs.df[,21], bold = fixed_concs.df[,36], underline = fixed_concs.df[,21] == FALSE) %>%
   column_spec(7, color = fixed_concs.df[,22], bold = fixed_concs.df[,37], underline = fixed_concs.df[,22] == FALSE) %>%
   column_spec(8, color = fixed_concs.df[,23], bold = fixed_concs.df[,38], underline = fixed_concs.df[,23] == FALSE) %>%
   column_spec(9, color = fixed_concs.df[,24], bold = fixed_concs.df[,39], underline = fixed_concs.df[,24] == FALSE) %>%
   column_spec(10, color = fixed_concs.df[,25], bold = fixed_concs.df[,40], underline = fixed_concs.df[,25] == FALSE) %>%
   column_spec(11, color = fixed_concs.df[,26], bold = fixed_concs.df[,41], underline = fixed_concs.df[,26] == FALSE) %>%
   column_spec(12, color = fixed_concs.df[,27], bold = fixed_concs.df[,42], underline = fixed_concs.df[,27] == FALSE) %>%
   column_spec(13, color = fixed_concs.df[,28], bold = fixed_concs.df[,43], underline = fixed_concs.df[,28] == FALSE) %>%
   column_spec(14, color = fixed_concs.df[,29], bold = fixed_concs.df[,44], underline = fixed_concs.df[,29] == FALSE) %>%
   column_spec(15, color = fixed_concs.df[,30], bold = fixed_concs.df[,45], underline = fixed_concs.df[,30] == FALSE) %>%
   column_spec(16, color = fixed_concs.df[,31], bold = fixed_concs.df[,46], underline = fixed_concs.df[,31] == FALSE) %>%
   save_kable(file = "tables/recommendations_sysdimet_change.pdf", keep_tex = TRUE)


```

```{r personal_effects_clustering}

k.max <- 8
set.seed(fixed_seed)
wss_effects <- sapply(1:k.max, function(k){kmeans(personal_effects, k, nstart=50, iter.max = 15)$tot.withinss})

df_effects <- data.frame(x = 1:k.max, y = wss_effects)

plot1 <- ggplot(data=df_effects, aes(x=x, y=y, group=1)) +
  geom_line() +
  geom_point() + 
  ggtitle("Difference in absolute reaction") +
  xlab("Number of clusters") +
  ylab("Difference between clusters")

plot1

# Number of cluster centers 
k <- 4

# Clustering using k-means
set.seed(fixed_seed)
km <- kmeans(personal_effects, centers = k)

recommendation_with_concpreds.df$effect_cluster <- km$cluster

personal_effect_clusters <- recommendation_with_concpreds.df %>% select(person_id, subject_code, effect_cluster)
```


```{r concentration_compositions_clustering}

k.max <- 8
set.seed(fixed_seed)
wss_effects <- sapply(1:k.max, function(k){kmeans(personal_effects, k, nstart=50, iter.max = 15)$tot.withinss})

df_effects <- data.frame(x = 1:k.max, y = wss_effects)

plot1 <- ggplot(data=df_effects, aes(x=x, y=y, group=1)) +
  geom_line() +
  geom_point() + 
  ggtitle("Difference in absolute reaction") +
  xlab("Number of clusters") +
  ylab("Difference between clusters")

plot1

# Number of cluster centers 
k <- 4

# Clustering using k-means
set.seed(fixed_seed)
km <- kmeans(personal_effects, centers = k)

recommendation_with_concpreds.df$effect_cluster <- km$cluster

personal_effect_clusters <- recommendation_with_concpreds.df %>% select(person_id, subject_code, effect_cluster)

recommendation_with_concpreds.df
personal_effects

```


```{r contribution_clustering}
library(tidyr)
library(ggplot2)

all_contributions.df <- data.frame()

for (person_id in 1:90)
{
  contr_file <- paste0("patient_summary/sysdimet/gamma_qr_mv/simulationX50_B50_A50_I50/details/contributions_",person_id,".rds")
  
  if (file.exists(contr_file)) {
    contributions.df <- readRDS(contr_file)
    all_contributions.df <- rbind(all_contributions.df, cbind(person_id, contributions.df))
  }
}

colnames(all_contributions.df) <- c("person_id", "nutrient", "concentration", "contributions")

# Step 1: Create a new column that combines nutrient and concentration into a single string
# This will serve as the new column names after pivoting
all_contributions.df <- all_contributions.df %>%
  filter(concentration == "fsins") %>%
  mutate(nutrient_concentration = paste(nutrient, concentration, sep = "_")) %>%
  select(-nutrient, -concentration)

# Step 2: Use pivot_wider() to spread the nutrient_concentration pairs across the columns,
# filling with contributions values
wide_contributions.df <- all_contributions.df %>%
  group_by(person_id) %>%
  pivot_wider(names_from = nutrient_concentration, values_from = contributions) %>%
  ungroup()

# Print the transformed data frame
#print(wide_contributions.df)

k.max <- 8
set.seed(fixed_seed)
wss_contributions <- sapply(1:k.max, function(k){kmeans(wide_contributions.df, k, nstart=50, iter.max = 15)$tot.withinss})

df_contributions <- data.frame(x = 1:k.max, y = wss_contributions)

plot1 <- ggplot(data=df_contributions, aes(x=x, y=y, group=1)) +
  geom_line() +
  geom_point() + 
  ggtitle("Difference in concentration contributions") +
  xlab("Number of clusters") +
  ylab("Difference between clusters")

plot1

# Number of cluster centers 
k <- 2

# Clustering using k-means
set.seed(fixed_seed)
km <- kmeans(wide_contributions.df, centers = k)

recommendation_with_concpreds.df$diet_cluster <- km$cluster

diet_clusters <- recommendation_with_concpreds.df %>% select(person_id, subject_code, diet_cluster)

```


```{r diet_strategies_plot, fig.width=7, fig.height=8}
library(dplyr)
library(ggplot2)

all_contributions.df <- data.frame()

simulation <- "X50_B50_A50_I50"

for (person_id in 1:90)
{
  contr_file <- paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/details/contributions_",person_id,".rds")
  
  if (file.exists(contr_file)) {
    contributions.df <- readRDS(contr_file)
    all_contributions.df <- rbind(all_contributions.df, cbind(person_id, contributions.df))
  }
}

colnames(all_contributions.df) <- c("person_id", "nutrient", "concentration", "contributions")

# Calculate mean contributions of nutrients for sorting them

mean_contributions <- all_contributions.df %>%
  filter(nutrient != 'base') %>%
  group_by(nutrient) %>%
  summarise(mean_abs_contribution = mean(abs(as.numeric(contributions)), na.rm = TRUE)) %>%
  ungroup() %>%
  select(nutrient, mean_abs_contribution) 

mean_contributions <- mean_contributions %>%  left_join(sysdimet_predictors, by = join_by(nutrient == Name)) 

# Join the mean_abs_contribution column to main data frame for sorting
df <- all_contributions.df %>%
  left_join(mean_contributions, by = "nutrient") 

# Baselevel of concentration is always sorted first
df[df$nutrient == "base",]$mean_abs_contribution <- 100

# Calculate the cumulative concentrations 
cumulative_concs <- df %>% 
     group_by(person_id, concentration) %>%
     arrange(desc(abs(mean_abs_contribution))) %>%
     mutate(predicted_concentration = cumsum(contributions)) %>%
     arrange(abs(mean_abs_contribution)) %>%
     mutate(nutrient=factor(nutrient, levels=nutrient)) %>%
     mutate(person_id=factor(person_id))


# Add subject codes for plotting and personal limits
subject_codes <- data.frame()
limit_data <- data.frame()
subjects <- levels(sysdimet$SUBJECT_ID)

for (person_id in as.numeric(levels(cumulative_concs$person_id)))
{
  subject_code <- subjects[person_id]
  subject_id <- as.numeric(gsub("S","",subject_code))
  
  subject_codes <- rbind(subject_codes, c(person_id, subject_id, subject_code))  
  
  # Normal ranges of concentration are personalized
  personal_info <- head(sysdimet[sysdimet$SUBJECT_ID == subject_code,],1)
  recommeded_concentrations <- mebn.get_personal_sysdimet_guidelines(personal_info)

  l.df <- data.frame(concentration = sysdimet_targets$Name, lower_limits = as.vector(recommeded_concentrations$lower_limits), upper_limits = as.vector(recommeded_concentrations$upper_limits))
  
  limit_data <- rbind(limit_data, l.df)
}

limit_data <- unique(limit_data)
colnames(subject_codes) <- c("person_id", "subject_id", "subject_code")

cumulative_concs <- cumulative_concs %>% left_join(subject_codes, join_by(person_id))
cumulative_concs$subject_code <- factor(cumulative_concs$subject_code)
cumulative_concs$subject_id <- factor(cumulative_concs$subject_id)

# Include personal diet clustering
#diet_clusters$person_id <- factor(diet_clusters$person_id)
#diet_clusters$diet_cluster <- factor(diet_clusters$diet_cluster)

#cumulative_concs <- cumulative_concs %>% left_join(diet_clusters, join_by(person_id))

# annotate("rect",ymin=-Inf, ymax=Inf, xmin=-Inf, xmax=fshdl_recommendations[1], alpha = .2) + 
# annotate("rect",ymin=-Inf, ymax=Inf, xmin=fshdl_recommendations[2], xmax=Inf, alpha = .2) + 

nutrient_labels <- setNames(cumulative_concs$ShortDescription, cumulative_concs$nutrient)
nutrient_labels <- paste0("+ ", nutrient_labels[!duplicated(names(nutrient_labels))])
nutrient_labels[16] <- "Baseline"

conc_labels <- c(fshdl = "HDL-C (mmol/l)", fsldl = "LDL-C (mmol/l)", fsins = "Insulin (mmol/l)", fskol = "TC (mmol/l)", fpgluk = "Glucose (mmol/l)")

#library("viridis")

simulation <- "X50_B50_A50_I50"
subjects_with_failed_concs <- readRDS(paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary_with_concpreds_and_current.rds"))

cumulative_concs$example <- cumulative_concs$subject_id %in%subjects_with_failed_concs[1:5,]$subject_code 
cumulative_concs$highlight_alpha <- ifelse(cumulative_concs$example, 1, 0.5)
cumulative_concs$highlight_width <- ifelse(cumulative_concs$example, 1.0, 0.5)

p <- ggplot(cumulative_concs) +
   geom_point(aes(x = predicted_concentration, y = nutrient, color = subject_id, alpha = highlight_alpha), size = 0.7, show.legend = FALSE) +
   geom_path(aes(x = predicted_concentration, y = nutrient, group = subject_id, color = subject_id, alpha = highlight_alpha, linewidth=highlight_width), show.legend = FALSE) +
   geom_vline(data = limit_data, aes(xintercept = upper_limits), linetype = "dashed", color = "#444444") +
   geom_vline(data = limit_data, aes(xintercept = lower_limits), linetype = "dashed", color = "#444444") +
   scale_linewidth_continuous(range = c(0.6, 0.8))  +
   scale_alpha_continuous(range = c(0.4, 1.0))  +
   facet_wrap(~concentration,scales = "free_x", labeller = labeller(concentration = conc_labels)) +
   scale_y_discrete(labels = nutrient_labels) + 
   theme_bw() +
   labs(x = element_blank(), y = element_blank(), color="Subject") +
   guides(color = guide_legend(override.aes = list(alpha = 1, size = 1)))  

 p

ggsave("figures/sysdimet_diet_strategies.pdf", plot = p)

```
```{r}
cumulative_concs[cumulative_concs$subject_code == "S104" & cumulative_concs$concentration == "fsins",]


```

```{r vitamin_effects, fig.width=8, fig.height=6}
library(ggplot2)

#conts <- as.data.frame(cumulative_concs[cumulative_concs$nutrient != "base",])
conts <- as.data.frame(cumulative_concs[cumulative_concs$nutrient %in% c("cvit","dvit"),])

conts$abs_contribution <- abs(as.numeric(conts$contributions))

p <- ggplot(conts, aes(fill=nutrient, y=abs_contribution, x=reorder(subject_code, -abs_contribution))) + 
    geom_bar(position="stack", stat="identity") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    facet_wrap(~concentration, scales = "free", labeller = labeller(concentration = conc_labels)) +
    xlab("Patients") +
    ylab("Absolute contribution of nutrients")
p
 
ggsave("figures/sysdimet_diet_vitamin_effects.pdf", plot = p)

```



```{r diet_strategies_table}
library(dplyr)
library(tidyr)
library(purrr)

# Get unique concentrations
concentrations <- unique(cumulative_concs$concentration)

# Loop through each concentration and create summary statistics
summary_dfs <- lapply(concentrations, function(conc) {
  cumulative_concs %>%
  ungroup() %>%
    select(nutrient, concentration, contributions) %>%
    filter(concentration == conc) %>%
    filter(nutrient != "base") %>%
    group_by(nutrient) %>%
    summarise(
      avg_contribution = round(mean(as.numeric(contributions)),2), 
      min_contribution = round(min(as.numeric(contributions)),2),
      max_contribution = round(max(as.numeric(contributions)),2)
    ) %>%
    select(nutrient, min_contribution, max_contribution) %>%
    # Rename the columns to include the concentration name
    rename_with(~ paste0(.x, "_", conc), -nutrient)
})

# unused additional summaries
#minmax_contribution = paste0(round(min(as.numeric(contributions)),2), " - ", round(max(as.numeric(contributions)),2))
#sd_contribution = round(sd(as.numeric(contributions)),2)

# Merge the summary data frames into a single data frame
strategy_summary.df <- reduce(summary_dfs, full_join, by = "nutrient")

strategy_summary.df <- strategy_summary.df %>%
  left_join(mean_contributions, by = "nutrient") %>%
  arrange(desc(mean_abs_contribution))

# ShortDescription comes from mean_contributions
strategy_summary.df$nutrient <- strategy_summary.df$ShortDescription
strategy_summary.df <- strategy_summary.df[order(strategy_summary.df$mean_abs_contribution, decreasing = TRUE),]
strategy_summary.df <- subset(strategy_summary.df, select = c(1:11))

kable(strategy_summary.df, "html", escape = F, booktabs = T, row.names = FALSE, digits = 2,align="lcccccccccc",
  col.names = c("Nutrient", "Min", "Max", "Min", "Max", "Min", "Max", "Min", "Max", "Min", "Max")) %>%
  add_header_above(c(" " = 1, "fS-HDL" = 2, "fS-LDL" = 2, "fS-Ins" = 2, "fS-Chol" = 2, "fp-Gluc" = 2), escape = F) %>%
  column_spec(1, width = "7em") %>%
  kable_styling(latex_options="scale_down") %>%  
  kable_styling(latex_options = c("basic", "condensed"), full_width = TRUE) %>%
  row_spec(0,bold=TRUE) #%>%
  #save_kable(file = "tables/sysdimet_diet_strategies.pdf", keep_tex = TRUE)

```


```{r diet_strategies_table_percentages}
library(dplyr)
library(tidyr)
library(purrr)

# Get unique concentrations
concentrations <- unique(cumulative_concs$concentration)

# Loop through each concentration and create summary statistics
# summary_dfs <- lapply(concentrations, function(conc) {
#   cumulative_concs %>%
#   ungroup() %>%
#     select(nutrient, concentration, contributions, predicted_concentration) %>%
#     filter(concentration == conc) %>%
#     filter(nutrient != "base") %>%
#     group_by(nutrient) %>%
#     summarise(
#       min_percentage = paste0(round(min(as.numeric(contributions)) / predicted_concentration * 100,1),"%"),
#       max_percentage = paste0(round(max(as.numeric(contributions)) / predicted_concentration * 100,1),"%"),
#       avg_percentage = paste0(round(mean(as.numeric(contributions)) / predicted_concentration * 100,1),"%")
#     ) %>%
#     select(nutrient, min_percentage, max_percentage) %>%
#     rename_with(~ paste0(.x, "_", conc), -nutrient)
# })


# Loop through each concentration and create summary statistics
summary_dfs <- lapply(concentrations, function(conc) {
  cumulative_concs %>%
  ungroup() %>%
    select(nutrient, concentration, contributions, predicted_concentration) %>%
    filter(concentration == conc) %>%
    filter(nutrient != "base") %>%
    mutate(contribution_percentage = as.numeric(contributions) / predicted_concentration * 100) %>%
    group_by(nutrient) %>%
    summarise(
      min_percentage = paste0(round(min(contribution_percentage),1),"%"),
      max_percentage = paste0(round(max(contribution_percentage),1),"%"),
      avg_percentage = paste0(round(mean(contribution_percentage),1),"%")
    ) %>%
    select(nutrient, min_percentage, max_percentage) %>%
    rename_with(~ paste0(.x, "_", conc), -nutrient)
})


# Merge the summary data frames into a single data frame
strategy_summary.df <- reduce(summary_dfs, full_join, by = "nutrient")

strategy_summary.df <- strategy_summary.df %>%
  left_join(mean_contributions, by = "nutrient") %>%
  arrange(desc(mean_abs_contribution))

# ShortDescription comes from mean_contributions
strategy_summary.df$nutrient <- strategy_summary.df$ShortDescription
strategy_summary.df <- strategy_summary.df[order(strategy_summary.df$mean_abs_contribution, decreasing = TRUE),]
strategy_summary.df <- subset(strategy_summary.df, select = c(1:11))

kable(strategy_summary.df, "latex", escape = F, booktabs = T, row.names = FALSE, digits = 2,align="lcccccccccc",
  col.names = c("Nutrient", "Min", "Max", "Min", "Max", "Min", "Max", "Min", "Max", "Min", "Max")) %>%
  add_header_above(c(" " = 1, "fS-HDL" = 2, "fS-LDL" = 2, "fS-Ins" = 2, "fS-Chol" = 2, "fp-Gluc" = 2), escape = F) %>%
  column_spec(1, width = "7em") %>%
  kable_styling(latex_options="scale_down") %>%  
  kable_styling(latex_options = c("basic", "condensed"), full_width = TRUE) %>%
  row_spec(0,bold=TRUE) %>%
  save_kable(file = "tables/sysdimet_diet_strategies_percentages.pdf", keep_tex = TRUE)

```
```{r}
# Testing percentages

cumulative_concs %>%
   ungroup() %>%
   filter(nutrient == "epa" & concentration == "fsins") %>%
   arrange(desc(contributions)) %>%
   select(person_id, contributions, predicted_concentration) %>%
   mutate(percentage = as.numeric(contributions) / predicted_concentration * 100) %>%
   arrange(desc(percentage))

```

```{r diet_strategies_table_percentages2}
library(dplyr)
library(tidyr)
library(purrr)

# Get unique concentrations
concentrations <- unique(cumulative_concs$concentration)

summary_dfs <- lapply(concentrations, function(conc) {
  cumulative_concs %>%
  ungroup() %>%
    select(nutrient, concentration, contributions, predicted_concentration) %>%
    filter(concentration == conc) %>%
    filter(nutrient != "base") %>%
    group_by(nutrient) %>%
    summarise(
      avg_contribution = round(mean(as.numeric(contributions)),2), 
      min_contribution = round(min(as.numeric(contributions)),2),
      max_contribution = round(max(as.numeric(contributions)),2),
      min_percentage = round(min(as.numeric(contributions)) / min(predicted_concentration) * 100,1),
      max_percentage = round(max(as.numeric(contributions)) / min(predicted_concentration) * 100,1),
      avg_percentage = round(mean(as.numeric(contributions)) / min(predicted_concentration) * 100,1)
    ) %>%
    select(nutrient, min_contribution, min_percentage, max_contribution, max_percentage, avg_percentage) %>%
    arrange(desc(avg_percentage)) %>%
    rename_with(~ paste0(.x, "_", conc), -nutrient)
})

# unused additional summaries
#minmax_contribution = paste0(round(min(as.numeric(contributions)),2), " - ", round(max(as.numeric(contributions)),2))
#sd_contribution = round(sd(as.numeric(contributions)),2)


# Merge the summary data frames into a single data frame
strategy_summary.df <- reduce(summary_dfs, full_join, by = "nutrient")

# Pretty nutrient names
all_effects <- data.frame(nutrient = sysdimet_predictors$Name, effect = sysdimet_predictors$ShortDescription)
strategy_summary.df <- strategy_summary.df %>% left_join(all_effects, by = "nutrient")
strategy_summary.df$nutrient <- strategy_summary.df$effect
strategy_summary.df <- subset(strategy_summary.df, select = -c(12))

# DF with percentages

strategy_summary_prec.df <- data.frame(nutrient = strategy_summary.df$nutrient)

strategy_summary_prec.df$min_fshdl <- paste0(strategy_summary.df$min_contribution_fshdl, " (", strategy_summary.df$min_percentage_fshdl,"%)")
strategy_summary_prec.df$max_fshdl <- paste0(strategy_summary.df$max_contribution_fshdl, " (", strategy_summary.df$max_percentage_fshdl,"%)")

strategy_summary_prec.df$min_fsldl <- paste0(strategy_summary.df$min_contribution_fsldl, " (", strategy_summary.df$min_percentage_fsldl,"%)")
strategy_summary_prec.df$max_fsldl <- paste0(strategy_summary.df$max_contribution_fsldl, " (", strategy_summary.df$max_percentage_fsldl,"%)")

strategy_summary_prec.df$min_fsins <- paste0(strategy_summary.df$min_contribution_fsins, " (", strategy_summary.df$min_percentage_fsins,"%)")
strategy_summary_prec.df$max_fsins <- paste0(strategy_summary.df$max_contribution_fsins, " (", strategy_summary.df$max_percentage_fsins,"%)")

strategy_summary_prec.df$min_fskol <- paste0(strategy_summary.df$min_contribution_fskol, " (", strategy_summary.df$min_percentage_fskol,"%)")
strategy_summary_prec.df$max_fskol <- paste0(strategy_summary.df$max_contribution_fskol, " (", strategy_summary.df$max_percentage_fskol,"%)")

strategy_summary_prec.df$min_fpgluk <- paste0(strategy_summary.df$min_contribution_fpgluk, " (", strategy_summary.df$min_percentage_fpgluk,"%)")
strategy_summary_prec.df$max_fpgluk <- paste0(strategy_summary.df$max_contribution_fpgluk, " (", strategy_summary.df$max_percentage_fpgluk,"%)")

kable(strategy_summary_prec.df, "latex", escape = F, booktabs = T, row.names = FALSE, digits = 2,align="lcccccccccc",
  col.names = c("Nutrient", "Min", "Max", "Min", "Max", "Min", "Max", "Min", "Max", "Min", "Max")) %>%
  add_header_above(c(" " = 1, "fS-HDL" = 2, "fS-LDL" = 2, "fS-Ins" = 2, "fS-Chol" = 2, "fp-Gluc" = 2), escape = F) %>%
  column_spec(1, width = "7em") %>%
  kable_styling(latex_options="scale_down") %>%  
  kable_styling(latex_options = c("basic", "condensed"), full_width= TRUE) %>%
  row_spec(0,bold=TRUE) %>%
  save_kable(file = "tables/sysdimet_diet_strategies_with_percentages.pdf", keep_tex = TRUE)

```

```{r}
library(kableExtra) # for HTML and Latex tables

# personal_effects is gathered in the previous block

effect_summary <- personal_effects %>% 
  group_by(effect) %>%
  dplyr::summarise(
                effect_avg = mean(as.numeric(value)),
                effect_sd = sd(as.numeric(value)),                 
                min_personal = min(as.numeric(value)),
                min_personal_lCI = as.numeric(value_lCI[which.min(as.numeric(value))]),
                min_personal_uCI = as.numeric(value_uCI[which.min(as.numeric(value))]),
                max_personal = max(as.numeric(value)),
                max_personal_lCI = as.numeric(value_lCI[which.max(as.numeric(value))]),
                max_personal_uCI = as.numeric(value_uCI[which.max(as.numeric(value))])
  ) %>%
  arrange(desc(abs(effect_avg))) %>%
  top_n(20)

effect_summary_table.df <- data.frame(effect <- effect_summary$effect, row.names = NULL)

effect_summary_table.df$effect_avg <- linebreak(paste0(format(round(effect_summary$effect_avg,2), nsmall=2)))
effect_summary_table.df$effect_sd <- linebreak(paste0(format(round(effect_summary$effect_sd,2), nsmall=2)))

effect_summary_table.df$min_personal <- linebreak(paste0(format(round(effect_summary$min_personal,2), nsmall=2),"\n$\\left[",format(round(effect_summary$min_personal_lCI,2), nsmall=2),"; ",format(round(effect_summary$min_personal_uCI,2), nsmall=2),"\\right]$"), align = "c")

effect_summary_table.df$max_personal <- linebreak(paste0(format(round(effect_summary$max_personal,2), nsmall=2),"\n$\\left[",format(round(effect_summary$max_personal_lCI,2), nsmall=2),"; ",format(round(effect_summary$max_personal_uCI,2), nsmall=2),"\\right]$"), align = "c")

colnames(effect_summary_table.df) <- c("effect", "effect_avg", "effect_sd", "min_personal", "max_personal")

# lookup dataframe for pretty effect names
all_effects <- expand.grid(predictor = sysdimet_predictors$Name, target = sysdimet_targets$Name)
all_descs <- expand.grid(predictor = sysdimet_predictors$ShortDescription, target = sysdimet_targets$ShortDescription)
effect_desc.df <- data.frame(effect <- paste0(all_effects$predictor,"_",all_effects$target), row.names = NULL)
effect_desc.df$desc <- paste0(effect <- paste0(all_descs$predictor," -> ",all_descs$target))
effect_desc.df$nutrient <- all_descs$predictor
effect_desc.df$concentration <- all_descs$target
colnames(effect_desc.df) <- c("effect", "effect_description", "nutrient", "concentration")

effect_summary_table.df <- effect_summary_table.df %>% left_join(effect_desc.df, by = "effect")

kable(effect_summary_table.df[c(6,2:5)], "latex", escape = F, booktabs = T, row.names = FALSE, digits = 2,align="lccccccccccc",
  col.names = c("Effect", "Avg. effect", "Effect sd.", "Min. personal effect", "Max personal effect")) %>%
  column_spec(1, width = "7em") %>%
  kable_styling(latex_options="scale_down") %>%  
  kable_styling(latex_options = c("basic", "condensed"), full_width = TRUE) %>%
  row_spec(0,bold=TRUE) %>%
  save_kable(file = "tables/sysdimet_effects.pdf", keep_tex = TRUE)
```


```{r diet_strategies_backup}
library(dplyr)

all_contributions.df <- data.frame()

for (person_id in 1:12)
{
  contr_file <- paste0("patient_summary/sysdimet/gamma_qr_mv/simulationX50_B50_A50_I50/details/contributions_",person_id,".rds")
  
  if (file.exists(contr_file)) {
    contributions.df <- readRDS(contr_file)
    all_contributions.df <- rbind(all_contributions.df, cbind(person_id, contributions.df))
  }
}

colnames(all_contributions.df) <- c("person_id", "nutrient", "concentration", "contributions")

# Calculate mean contributions of nutrients for sorting them
mean_contributions <- all_contributions.df %>%
  filter(concentration == 'fpgluk') %>%
  filter(nutrient != 'base') %>%
  group_by(concentration, nutrient) %>%
  summarise(mean_abs_contribution = mean(abs(as.numeric(contributions)), na.rm = TRUE)) %>%
  ungroup() %>%
  select(nutrient, mean_abs_contribution)

# Join the mean_abs_contribution column to main data frame for sorting
df <- all_contributions.df %>%
  filter(concentration == 'fpgluk') %>%
#  filter(person_id %in% c(1,3)) %>%
  left_join(mean_contributions, by = "nutrient") 

# Baselevel of concentration is always sorted first
df[df$nutrient == "base",]$mean_abs_contribution <- 100

# Calculate the cumulative concentrations 
cumulative_concs <- df %>% 
    group_by(person_id, concentration) %>%
    arrange(desc(abs(mean_abs_contribution))) %>%
    mutate(predicted_concentration = cumsum(contributions)) %>%
    arrange((abs(mean_abs_contribution))) %>%
    mutate(nutrient=factor(nutrient, levels=nutrient)) %>%
    mutate(person_id=factor(person_id))

ggplot(cumulative_concs) +
  geom_point(aes(x = predicted_concentration, y = nutrient, color = person_id), size = 1.0, show.legend = FALSE) +
  geom_path(aes(x = predicted_concentration, y = nutrient, group = person_id, color = person_id), linewidth=0.3)

#ggplot(all_contributions.df) +
  #geom_path(aes(x=contributions, y=queried_nodes, color=contributions < 0), size = 0.7, show.legend = FALSE) 
  #geom_vline(xintercept=0, linetype="solid", color = "black", linewidth=0.3) +
  #facet_wrap(~concentration) +
  #theme_bw() +
  #labs(x = element_blank(), y = element_blank()) +
  #theme(axis.text.x = element_blank())
 
```


# TRASHCAN


```{r concentration_predictions}
  library(rstan)
  library(igraph)
  library(stringr)
  
  source("mebn/v3/MEBNv3.r")

  queried_nodes <- sysdimet_datadesc[sysdimet_datadesc$Condition >= 100,]$Name
  patient_summary <- readRDS("patient_summary/sysdimet/gamma_qr_mv/simulationX50_B50_A50_I50/recommendation_summary.rds")

  for (subject_id in 1:37) {
    
    subject_id <- 1
    
    print(subject_id)

    graph_dir <- paste0("graphs/sysdimet/gamma_qr_mv/",subject_id)
    reaction_graph <- read.graph(paste0(graph_dir, "/personal_graph.graphml"), "graphml")
    
    org_stats <- data.frame(name = subset(sysdimet_predictors$Name, sysdimet_predictors$Distribution == "Gaussian"))
    org_stats$mean <- sapply(org_stats$name, function(x) mean(sysdimet[[x]]))
    org_stats$sd <- sapply(org_stats$name, function(x) sd(sysdimet[[x]]))
  
    queried_nodes <- sysdimet_datadesc[sysdimet_datadesc$Condition >= 100,]$Name
    queried_nodes_lCI <- paste0(queried_nodes,"_lCI")
    queried_nodes_uCI <- paste0(queried_nodes,"_uCI")
  
    params <- mebn.extract_parameters_from_graph(reaction_graph, beta_point_est = "mean", param_point_est = "mean", X_point_est = "mean", queried_nodes = queried_nodes)
    
    Q_values <- patient_summary %>% filter(person_id == subject_id) %>% select(all_of(queried_nodes))
    Q_values_lCI <- patient_summary %>% filter(person_id == subject_id) %>% select(all_of(queried_nodes_lCI))
    Q_values_uCI <- patient_summary %>% filter(person_id == subject_id) %>% select(all_of(queried_nodes_uCI))
    
    Q_values_norm <- (as.numeric(Q_values) - org_stats[org_stats$name == colnames(Q_values),]$mean) / org_stats[org_stats$name == colnames(Q_values),]$sd
    Q_values_lCI_norm <- (as.numeric(Q_values_lCI) - org_stats[org_stats$name == colnames(Q_values),]$mean) / org_stats[org_stats$name == colnames(Q_values),]$sd
    Q_values_uCI_norm <- (as.numeric(Q_values_uCI) - org_stats[org_stats$name == colnames(Q_values),]$mean) / org_stats[org_stats$name == colnames(Q_values),]$sd
    
    fshdl_mu <- params$intercept_point[1] + params$X_evidence_point %*% params$X_beta_point[1,] + Q_values_norm %*% params$Q_beta_point[1,]
    fsldl_mu <- params$intercept_point[2] + params$X_evidence_point %*% params$X_beta_point[2,] + Q_values_norm %*% params$Q_beta_point[2,]
    fsins_mu <- params$intercept_point[3] + params$X_evidence_point %*% params$X_beta_point[3,] + Q_values_norm %*% params$Q_beta_point[3,]
    fskol_mu <- params$intercept_point[4] + params$X_evidence_point %*% params$X_beta_point[4,] + Q_values_norm %*% params$Q_beta_point[4,]
    fpgluk_mu <- params$intercept_point[5] + params$X_evidence_point %*% params$X_beta_point[5,] + Q_values_norm %*% params$Q_beta_point[5,]
    
    resulting_conc_mu <- c(fshdl_mu,fsldl_mu,fsins_mu,fskol_mu,fpgluk_mu)
  
    quant_limit <- 0.9
    fshdl_mu_lCI <- qgamma(1-quant_limit, shape=params$alpha_point[1], rate=params$alpha_point[1]/fshdl_mu)
    fshdl_mu_uCI <- qgamma(quant_limit, shape=params$alpha_point[1], rate=params$alpha_point[1]/fshdl_mu)

    fsldl_mu_lCI <- qgamma(1-quant_limit, shape=params$alpha_point[2], rate=params$alpha_point[2]/fsldl_mu)
    fsldl_mu_uCI <- qgamma(quant_limit, shape=params$alpha_point[2], rate=params$alpha_point[2]/fsldl_mu)

    fsins_mu_lCI <- qgamma(1-quant_limit, shape=params$alpha_point[3], rate=params$alpha_point[3]/fsins_mu)
    fsins_mu_uCI <- qgamma(quant_limit, shape=params$alpha_point[3], rate=params$alpha_point[3]/fsins_mu)

    fskol_mu_lCI <- qgamma(1-quant_limit, shape=params$alpha_point[4], rate=params$alpha_point[4]/fskol_mu)
    fskol_mu_uCI <- qgamma(quant_limit, shape=params$alpha_point[4], rate=params$alpha_point[4]/fskol_mu)

    fpgluk_mu_lCI <- qgamma(1-quant_limit, shape=params$alpha_point[5], rate=params$alpha_point[5]/fpgluk_mu)
    fpgluk_mu_uCI <- qgamma(quant_limit, shape=params$alpha_point[5], rate=params$alpha_point[5]/fpgluk_mu)

    resulting_conc_mu_lCI <- c(fshdl_mu_lCI,fsldl_mu_lCI,fsins_mu_lCI,fskol_mu_lCI,fpgluk_mu_lCI)
    resulting_conc_mu_uCI <- c(fshdl_mu_uCI,fsldl_mu_uCI,fsins_mu_uCI,fskol_mu_uCI,fpgluk_mu_uCI)
    
    patient_summary[patient_summary$person_id == subject_id,]$fshdl <- fshdl_mu
    patient_summary[patient_summary$person_id == subject_id,]$fshdl_lCI <- fshdl_mu_lCI
    patient_summary[patient_summary$person_id == subject_id,]$fshdl_uCI <- fshdl_mu_uCI
  
    patient_summary[patient_summary$person_id == subject_id,]$fsldl <- fsldl_mu
    patient_summary[patient_summary$person_id == subject_id,]$fsldl_lCI <- fsldl_mu_lCI
    patient_summary[patient_summary$person_id == subject_id,]$fsldl_uCI <- fsldl_mu_uCI
  
    patient_summary[patient_summary$person_id == subject_id,]$fsins <- fsins_mu
    patient_summary[patient_summary$person_id == subject_id,]$fsins_lCI <- fsins_mu_lCI
    patient_summary[patient_summary$person_id == subject_id,]$fsins_uCI <- fsins_mu_uCI

    patient_summary[patient_summary$person_id == subject_id,]$fskol <- fskol_mu
    patient_summary[patient_summary$person_id == subject_id,]$fskol_lCI <- fskol_mu_lCI
    patient_summary[patient_summary$person_id == subject_id,]$fskol_uCI <- fskol_mu_uCI

    patient_summary[patient_summary$person_id == subject_id,]$fpgluk <- fpgluk_mu
    patient_summary[patient_summary$person_id == subject_id,]$fpgluk_lCI <- fpgluk_mu_lCI
    patient_summary[patient_summary$person_id == subject_id,]$fpgluk_uCI <- fpgluk_mu_uCI
    
  }
  
  saveRDS(patient_summary, paste0("patient_summary/sysdimet/gamma_qr_mv/simulationX50_B50_A50_I50/recommendation_summary_with_concpreds.rds"))

```



```{r personal_graphs_comparison, eval=TRUE, fig.height = 8, fig.width = 5, fig.align = "left", echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.cap="Two subjects were picked from differently reacting clusters and their personally predicted reaction graphs show differences from the general behaviour. The figure is plotted with iGraph package for R language (v 1.2.6, https://igraph.org/r)."}
source("mebn/MEBN.r")
require(igraph)
personal_graph1 <- read.graph("graphs/personal_insample_graph_s01.graphml", "graphml")
personal_graph2 <- read.graph("graphs/personal_insample_graph_s104.graphml", "graphml")

par(mfrow=c(2,1))
layout <- mebn.plot_personal_effects(personal_graph1, 10, graph_layout, colorImage = !RenderArticleFigures)
title("Subject 1 from cluster 3 with high insulin reactions",cex.main=0.7)
layout <- mebn.plot_personal_effects(personal_graph2, 10, graph_layout, colorImage = !RenderArticleFigures)
title("Subject 2 from cluster 2 with moderate insulin reactions",cex.main=0.7)
```

```{r}
source("mebn/v3/MEBNv3.r")
require(igraph)
#library(tidygraph)

graph_person_id <- 4

personal_graph <- read.graph(paste0("graphs/sysdimet/gamma_qr_mv/", graph_person_id, "/personal_graph.graphml"), "graphml")

nutrients <- V(personal_graph)[V(personal_graph)$type == 100 | V(personal_graph)$type == 200]

name_lookup <- data.frame(Name = nutrients$name) %>% inner_join(sysdimet_datadesc, by = join_by(Name))

layout <- mebn.plot_personal_effects(personal_graph, 80, name_lookup$ShortDescription, graph_layout = NULL)

```

```{r}
check_failed_fpgluk <- function(graph_person_id, personal_info, recommeded_concentrations) {
  
  fshdl_min <- recommeded_concentrations$lower_limits[1]
  fsldl_min <- recommeded_concentrations$lower_limits[2]
  fsins_min <- recommeded_concentrations$lower_limits[3]
  fskol_min <- recommeded_concentrations$lower_limits[4]
  fpgluk_min <- recommeded_concentrations$lower_limits[5]
  fshdl_max <- recommeded_concentrations$upper_limits[1]
  fsldl_max <- recommeded_concentrations$upper_limits[2]
  fsins_max <- recommeded_concentrations$upper_limits[3]
  fskol_max <- recommeded_concentrations$upper_limits[4]
  fpgluk_max <- recommeded_concentrations$upper_limits[5]  
  
  graph_dir <- paste0("graphs/sysdimet/gamma_qr_mv/",graph_person_id)
  personal_graph <- read.graph(paste0(graph_dir, "/personal_graph.graphml"), "graphml")
  
  current_fshdl <- V(personal_graph)["fshdl"]$value_mean
  current_fsldl <- V(personal_graph)["fsldl"]$value_mean
  current_fsins <- V(personal_graph)["fsins"]$value_mean
  current_fskol <- V(personal_graph)["fskol"]$value_mean
  current_fpgluk <- V(personal_graph)["fpgluk"]$value_mean
  
  is_failing <- current_fshdl < fshdl_min | current_fshdl > fshdl_max |
    current_fsldl < fsldl_min | current_fsldl > fsldl_max |
    current_fsins < fsins_min | current_fsins > fsins_max |
    current_fskol < fskol_min | current_fskol > fskol_max |
    current_fpgluk < fpgluk_min | current_fpgluk > fpgluk_max 

  is_failing <- current_fpgluk < fpgluk_min | current_fpgluk > fpgluk_max 
  
  return(is_failing)
}

```

```{r difficult_limits}
library(ggplot2)
library(dplyr)

preds.df <- readRDS(paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary_with_concpreds_and_current.rds"))

#limit_reasoning.df <- data.frame(subject_code = sprintf("S%02d", preds.df$subject_code))

limit_reasoning.df <- data.frame(matrix(ncol = 2, nrow = 0), row.names = NULL)

for (i in 1:nrow(preds.df)) {
  p <- preds.df[i,]
  
  subject_code <- sprintf("S%02d", p$subject_code)
  personal_info <- head(sysdimet[sysdimet$SUBJECT_ID == subject_code,],1)
  recommeded_concentrations <- mebn.get_personal_sysdimet_guidelines(personal_info)
  
  diffs.df <- data.frame(matrix(ncol = 0, nrow = 1), row.names = NULL)
  
  for (t in 1:5) {
    ul <- recommeded_concentrations$upper_limits[t]
    t_name <- sysdimet_targets[t,]$Name
    pred_ul <- p[t_name]
  
    t_diff <- abs(ul-pred_ul)
    
    diffs.df[t_name] <- t_diff 
  }   
  
  limit_reasoning.df <- rbind(limit_reasoning.df, c(subject_code = subject_code, diffs.df))
}

fpgluk_diff <- limit_reasoning.df[,c(1,6)]

fpgluk_conts <- cumulative_concs[cumulative_concs$concentration == "fpgluk" & cumulative_concs$nutrient != "base",]

reason.df <- fpgluk_diff %>% inner_join(fpgluk_conts, by="subject_code")

reason.df

#  filter(subject_code == "S104") %>%

fpgluk_reason.df <- reason.df %>%
  group_by(subject_code) %>%
  summarise(diff = min(fpgluk), neg_cont = sum(contributions < 0))

ggplot(fpgluk_reason.df) + 
    geom_point(aes(x=diff, y=neg_cont))



conts <- as.data.frame(cumulative_concs[cumulative_concs$nutrient != "base",])
conts <- as.data.frame(cumulative_concs[cumulative_concs$nutrient %in% c("cvit"),])
conts <- as.data.frame(cumulative_concs[cumulative_concs$nutrient %in% c("cvit","dvit"),])

conts$abs_contribution <- abs(as.numeric(conts$contributions))

ggplot(conts, aes(fill=nutrient, y=abs_contribution, x=reorder(subject_code, -abs_contribution))) + 
    geom_bar(position="stack", stat="identity") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    facet_wrap(~concentration,scales = "free_y", labeller = labeller(concentration = conc_labels)) 

limit_reasoning.df
```


```{r diet_strategies_plot_reasoning, fig.width=7, fig.height=8}
library(dplyr)
library(ggplot2)

all_contributions.df <- data.frame()

simulation <- "X50_B50_A50_I50"

for (person_id in 1:90)
{
  contr_file <- paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/details/contributions_",person_id,".rds")
  
  if (file.exists(contr_file)) {
    contributions.df <- readRDS(contr_file)
    all_contributions.df <- rbind(all_contributions.df, cbind(person_id, contributions.df))
  }
}

colnames(all_contributions.df) <- c("person_id", "nutrient", "concentration", "contributions")

# Calculate mean contributions of nutrients for sorting them

mean_contributions <- all_contributions.df %>%
  filter(nutrient != 'base') %>%
  group_by(nutrient) %>%
  summarise(mean_abs_contribution = mean(abs(as.numeric(contributions)), na.rm = TRUE)) %>%
  ungroup() %>%
  select(nutrient, mean_abs_contribution) 

mean_contributions <- mean_contributions %>%  left_join(sysdimet_predictors, by = join_by(nutrient == Name)) 

# Join the mean_abs_contribution column to main data frame for sorting
df <- all_contributions.df %>%
  left_join(mean_contributions, by = "nutrient") 

# Baselevel of concentration is always sorted first
df[df$nutrient == "base",]$mean_abs_contribution <- 100

# Calculate the cumulative concentrations 
cumulative_concs <- df %>% 
     group_by(person_id, concentration) %>%
     arrange(desc(abs(mean_abs_contribution))) %>%
     mutate(predicted_concentration = cumsum(contributions)) %>%
     arrange(abs(mean_abs_contribution)) %>%
     mutate(nutrient=factor(nutrient, levels=nutrient)) %>%
     mutate(person_id=factor(person_id))


# Add subject codes for plotting and personal limits
subject_codes <- data.frame()
limit_data <- data.frame()
subjects <- levels(sysdimet$SUBJECT_ID)

for (person_id in as.numeric(levels(cumulative_concs$person_id)))
{
  #print(person_id)  #12, 26
  #print(subject_code) # S104, S108

  subject_code <- subjects[person_id]
  subject_id <- as.numeric(gsub("S","",subject_code))
  
  subject_codes <- rbind(subject_codes, c(person_id, subject_id, subject_code))  
  
  # Normal ranges of concentration are personalized
  personal_info <- head(sysdimet[sysdimet$SUBJECT_ID == subject_code,],1)
  recommeded_concentrations <- mebn.get_personal_sysdimet_guidelines(personal_info)

  l.df <- data.frame(concentration = sysdimet_targets$Name, lower_limits = as.vector(recommeded_concentrations$lower_limits), upper_limits = as.vector(recommeded_concentrations$upper_limits))
  
  limit_data <- rbind(limit_data, l.df)
}

limit_data <- unique(limit_data)
colnames(subject_codes) <- c("person_id", "subject_id", "subject_code")

cumulative_concs <- cumulative_concs %>% left_join(subject_codes, join_by(person_id))
cumulative_concs$subject_code <- factor(cumulative_concs$subject_code)
cumulative_concs$subject_id <- factor(cumulative_concs$subject_id)

nutrient_labels <- setNames(cumulative_concs$ShortDescription, cumulative_concs$nutrient)
nutrient_labels <- paste0("+ ", nutrient_labels[!duplicated(names(nutrient_labels))])
nutrient_labels[16] <- "Baseline"

conc_labels <- c(fshdl = "fS-HDL (mmol/l)", fsldl = "fS-LDL (mmol/l)", fsins = "fS-Ins (mmol/l)", fskol = "fS-Chol (mmol/l)", fpgluk = "fP-Gluc (mmol/l)")


simulation <- "X50_B50_A50_I50"
subjects_with_failed_concs <- readRDS(paste0("patient_summary/sysdimet/gamma_qr_mv/simulation",simulation,"/recommendation_summary_with_concpreds_and_current.rds"))

cumulative_concs$example <- cumulative_concs$subject_id %in%subjects_with_failed_concs[1:5,]$subject_code 
cumulative_concs$highlight_alpha <- ifelse(cumulative_concs$example, 1, 0.5)
cumulative_concs$highlight_width <- ifelse(cumulative_concs$example, 1.0, 0.5)

cumulative_concs <- cumulative_concs %>% filter(subject_code == "S104" | subject_code == "S105" | subject_code == "S64" | subject_code == "S48"| subject_code == "S69" | subject_code == "S12")

p <- ggplot(cumulative_concs) +
   geom_point(aes(x = predicted_concentration, y = nutrient, color = subject_id), alpha = 0.8, size = 0.8, show.legend = FALSE) +
   geom_path(aes(x = predicted_concentration, y = nutrient, group = subject_id, color = subject_id), alpha = 0.8, linewidth=0.6, show.legend = TRUE) +
   geom_vline(data = limit_data, aes(xintercept = upper_limits), linetype = "dashed", color = "#444444") +
   geom_vline(data = limit_data, aes(xintercept = lower_limits), linetype = "dashed", color = "#444444") +
   scale_linewidth_continuous(range = c(0.6, 0.8))  +
   scale_alpha_continuous(range = c(0.4, 1.0))  +
   facet_wrap(~concentration,scales = "free_x", labeller = labeller(concentration = conc_labels)) +
   scale_y_discrete(labels = nutrient_labels) + 
   theme_bw() +
   labs(x = element_blank(), y = element_blank(), color="Subject") +
   guides(color = guide_legend(override.aes = list(alpha = 1, size = 1)))  

 p

```


```{r}
cumulative_concs
intake.df[intake.df$subject_code=="104",]
```



